In [1]:
import numpy as np

In [14]:
patientid=np.array([76,102,103,90,105])
HR=np.array([72,110,55,130,88])
sts=np.where(HR>100,"CRITICAL","STABLE")
print("patientid",patientid)
print("HR",HR)
print("satus",sts)

patientid [ 76 102 103  90 105]
HR [ 72 110  55 130  88]
satus ['STABLE' 'CRITICAL' 'STABLE' 'CRITICAL' 'STABLE']

In [4]:
tem=np.array([34,46,23,0,43,0,20])
con=tem!=0
filtered=tem[con]
avrtem=filtered.mean()
clean=np.where(tem==0,avrtem,tem)
clean

array([34. , 46. , 23. , 33.2, 43. , 33.2, 20. ])

In [10]:
apdatetem=tem[tem[0:]>37]
print("tem>37",apdatetem)

tem>37 [46 43]

In [12]:
apdatetem2=clean[clean[0:]>37]
print("tem>37",apdatetem2)

tem>37 [46. 43.]

In [17]:
age=np.array([25,65,45,70])
pb=np.array([120,15,135,160])
risk=np.where(((age>60)|(pb>140)),"RISK","SAFE")
risk

array(['SAFE', 'RISK', 'SAFE', 'RISK'], dtype='<U4')

In [20]:
sal=np.array([400,500,550,600,700,300])
condition=sal>=500
salabdate=np.where(condition,(sal+100),(sal+50))
salabdate

array([450, 600, 650, 700, 800, 350])

In [21]:
grade=np.array([30,50,60,70,48,90,86,98])
resultt=np.where(grade>=85,"A",np.where((grade>=70),"B","C"))
resultt

array(['C', 'C', 'C', 'B', 'C', 'A', 'A', 'A'], dtype='<U1')

In [26]:
PRICE=np.array([50,120,30,49,120,134])
FPRICE=np.where(PRICE>100,PRICE*0.8,PRICE*0.9)
FPRICE

array([ 45. ,  96. ,  27. ,  44.1,  96. , 107.2])

In [27]:
age=np.array([25,65,45,70])
pb=np.array([120,15,135,160])
risk=np.where(((age>60)&(pb>140)),"RISK","SAFE")
risk

array(['SAFE', 'SAFE', 'SAFE', 'RISK'], dtype='<U4')

In [31]:
import numpy as np

In [33]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [35]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [38]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [39]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: numpy>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
import pandas as pd

In [41]:
data=[1,2,3,4,5]
seris=pd.Series(data)
seris

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [43]:
data=[1,2,3,4,5]
seris=pd.Series((data),index=['a','b','c','d','e'])
seris.index.name='myindex'
seris

myindex
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [60]:
data=[1,2,3,4,5]
seris=pd.Series((data),index=['a','b','c','d','e'])
seris.index.name='myindex'
seris.index=[1,1,22,1,1]
seris

1     1
1     2
22    3
1     4
1     5
dtype: int64

In [45]:
seris.values

array([1, 2, 3, 4, 5], dtype=int64)

In [46]:
max(seris.values)

5

In [48]:
import numpy as np
avr=np.mean(seris.values)
avr

3.0

In [49]:
seris.index

Int64Index([1, 1, 1, 1, 1], dtype='int64')

In [58]:
seris.name="fscore"
seris.name

'fscore'

In [61]:
seris[22]

3

In [62]:
seris[seris<3]

1    1
1    2
dtype: int64

In [64]:
[seris<3]

[1      True
 1      True
 22    False
 1     False
 1     False
 dtype: bool]

In [68]:
if 5 in seris:
    print(False)

In [70]:
dic=seris.to_dict()
dic

{1: 5, 22: 3}

In [76]:
s=pd.Series(dic)
s

1     5
22    3
dtype: int64

In [80]:
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000], index = ['China','Germany','Japan','USA'])
countriesPop.name = "countriesPop"
countriesPop

China      8700000
Germany    4300000
Japan      3000000
USA        2100000
Name: countriesPop, dtype: int64

In [81]:
pd.isnull(countriesPop)

China      False
Germany    False
Japan      False
USA        False
Name: countriesPop, dtype: bool

In [85]:
pd.notnull(countriesPop).sum()

4

In [87]:
import numpy as np
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000,np.nan], index = ['China','Germany','Japan','USA','oman'])
countriesPop.name = "countriesPop"
pd.isnull(countriesPop)

China      False
Germany    False
Japan      False
USA        False
oman        True
Name: countriesPop, dtype: bool

In [88]:
pd.isnull(countriesPop).sum()

1

In [90]:
countriesPop1 = pd.Series([
8700000,
4300000,
3000000,
2100000], index = ['China','Germany','Japan','USA'])
countriesPop2 = pd.Series([
8700000,
4300000,
3000000,
2100000], index = ['China','Germany','Japan','USA'])
countriesPop1+countriesPop2

China      17400000
Germany     8600000
Japan       6000000
USA         4200000
dtype: int64

In [94]:
se=pd.Series({"m":85,"si":90,"e":78})
print(se[se>80])
print([se>80])

m     85
si    90
dtype: int64
[m      True
si     True
e     False
dtype: bool]

In [98]:

s2=pd.Series([10,None,None,30,50])
print(s2.isna().sum())
avr=s2.mean()
print(s2.fillna(3))

2
0    10.0
1     3.0
2     3.0
3    30.0
4    50.0
dtype: float64

In [99]:
name=pd.Series(["ali","ahmed","ammar","salim"])
print(name.str.upper())
print(name[name.str.len()>4])

0      ALI
1    AHMED
2    AMMAR
3    SALIM
dtype: object
1    ahmed
2    ammar
3    salim
dtype: object

In [104]:
countriesPop3 = pd.Series([
8700000,
4300000,
3000000,
2100000], index = ['China','Germany','Japan','USA'])
countriesPop3.rename(index={"China":"oman"},inplace=True)
countriesPop3
#new vlu
countriesPop3["UAE"]=3000000
countriesPop3

oman       8700000
Germany    4300000
Japan      3000000
USA        2100000
UAE        3000000
dtype: int64

In [108]:
A=countriesPop3.sort_values()
A

USA        2100000
Japan      3000000
UAE        3000000
Germany    4300000
oman       8700000
dtype: int64

In [109]:
A=countriesPop3.sort_index()
A

Germany    4300000
Japan      3000000
UAE        3000000
USA        2100000
oman       8700000
dtype: int64

In [114]:
countriesPop3 = pd.Series([
8700000,
4300000,
3000000,
2100000], index = ['China','Germany','Japan','USA'])
countriesPop3.rename(index={"China":"oman"},inplace=True)
b=countriesPop3.value_counts()
b

8700000    1
4300000    1
3000000    1
2100000    1
dtype: int64

In [117]:
print("Exercise 12")
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([15, 15, 35])
s1>s2
s1==s2

Exercise 12

0    False
1    False
2    False
dtype: bool

In [118]:
sales = pd.Series([200, 450, 300, 150, 500],
                  index=["Mon", "Tue", "Wed", "Thu", "Fri"])

# Total sales
print("Total:", sales.sum())

# Average sales
print("Average:", sales.mean())

# Max sales day
print("Highest day:", sales.idxmax())

# Sales > 300
print("Days with sales > 300:")
print(sales[sales > 3])

Total: 1600
Average: 320.0
Highest day: Fri
Days with sales > 300:
Mon    200
Tue    450
Wed    300
Thu    150
Fri    500
dtype: int64

In [120]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}
df=pd.DataFrame(data)
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [121]:
df.head(2)

    Name  Age         City
0  Alice   24     New York
1    Bob   27  Los Angeles

In [122]:
df.tail(2)

      Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [125]:
print(df.info())
print(df.describe())
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
None
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

In [126]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [128]:
print(df[['Name','Age']])

AttributeError: 'list' object has no attribute 'mean'

In [129]:
print(df.iloc[0])

Name       Alice
Age           24
City    New York
Name: 0, dtype: object

In [130]:
print(df.loc[1])

Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object

In [131]:
print(df.loc[2])

Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

In [133]:
pip install Kagglehub

Defaulting to user installation because normal site-packages is not writeable
Collecting Kagglehub
  Downloading kagglehub-0.3.13-py3-none-any.whl (68 kB)
     ---------------------------------------- 68.3/68.3 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (4.64.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (2.28.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (21.3)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (6.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->Kagglehub) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (1.26.11)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->Kagglehub) (0.4.5)
Installing collected packages: Kagglehub
Successfully installed Kagglehub-0.3.13
Note: you may need to restart the kernel to use updated packages.

In [135]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Temp\ipykernel_7348\874124.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/sudhirsingh108/data-science-students?dataset_version_number=1&file_name=data_science_student_marks.csv...

100%|█████████████████████████████████████████████████████████████████████████████| 15.1k/15.1k [00:00<00:00, 3.10MB/s]

First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87
1           5    Tokyo   24         99           95            89
2           6   Berlin   22         72           70            99
3           7   London   23         97           90            74
4           8    Tokyo   22         91           71            79

   power_bi_marks  english_marks
0              82             75
1              86             82
2              79             77
3              72             85
4              80             75

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      497 non-null    int64
 1   location        497 non-null    object
 2   age             497 non-null    int64
 3   sql_marks       497 non-null    int64
 4   excel_marks     497 non-null    int64
 5   python_marks    497 non-null    int64
 6   power_bi_marks  497 non-null    int64
 7   english_marks   497 non-null    int64
dtypes: int64(7), object(1)
memory usage: 31.2+ KB

In [137]:
df.describe()

,student_id,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
count,497.000000,497.000000,497.000000,497.000000,497.000000,497.000000,497.000000
mean,252.000000,21.380282,84.661972,85.384306,85.388330,84.545272,84.824950
std,143.615807,2.205714,8.745415,8.782497,8.878668,8.903066,9.060479
min,4.000000,18.000000,70.000000,70.000000,70.000000,70.000000,70.000000
25%,128.000000,20.000000,78.000000,78.000000,77.000000,77.000000,77.000000
50%,252.000000,21.000000,85.000000,86.000000,86.000000,84.000000,85.000000
75%,376.000000,23.000000,92.000000,93.000000,94.000000,92.000000,93.000000
max,500.000000,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [138]:
import numpy as np

In [139]:
df.value_counts()

student_id  location  age  sql_marks  excel_marks  python_marks  power_bi_marks  english_marks
4           Sydney    24   95         99           87            82              75               1
331         Paris     21   70         86           77            88              91               1
344         New York  21   96         83           86            78              74               1
343         New York  19   99         72           88            92              90               1
342         London    18   95         74           100           89              78               1
                                                                                                 ..
165         Sydney    19   83         71           95            72              84               1
164         Tokyo     24   74         95           93            84              81               1
163         Paris     21   87         95           97            85              96               1
162         Sydney    18   70         74           95            84              89               1
500         London    22   85         87           93            70              86               1
Length: 497, dtype: int64

In [140]:
df.isnull().sum()

student_id        0
location          0
age               0
sql_marks         0
excel_marks       0
python_marks      0
power_bi_marks    0
english_marks     0
dtype: int64

In [143]:
df['location'].unique()

array(['Sydney', 'Tokyo', 'Berlin', 'London', 'Toronto', 'Melbourne',
       'Paris', 'Los Angeles', 'New York'], dtype=object)

In [145]:
df['location'].value_counts()

Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: location, dtype: int64

In [146]:
df['sql_marks'].mean()

84.66197183098592

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Temp\ipykernel_17592\874124.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87
1           5    Tokyo   24         99           95            89
2           6   Berlin   22         72           70            99
3           7   London   23         97           90            74
4           8    Tokyo   22         91           71            79

   power_bi_marks  english_marks
0              82             75
1              86             82
2              79             77
3              72             85
4              80             75

In [3]:
df.iloc[[1,6]]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
6,10,Tokyo,18,77,87,100,98,93

In [5]:
df.iloc[1:6]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
5,9,Toronto,20,93,88,75,93,72

In [6]:
df.iloc[1:6,0:2]

   student_id location
1           5    Tokyo
2           6   Berlin
3           7   London
4           8    Tokyo
5           9  Toronto

In [10]:
df.iloc[0:21,7]

0      75
1      82
2      77
3      85
4      75
5      72
6      93
7      72
8      94
9      86
10     96
11     71
12     84
13     85
14     71
15     83
16     98
17     96
18     85
19    100
20     75
Name: english_marks, dtype: int64

In [11]:
df.iloc[0:21,7].mean()

83.57142857142857

In [12]:
df.iloc[0:21,7].max()

100

In [14]:
#df.iloc[0:21,7].mean().idxmax()
df.iloc[0:21,7].idxmax()

19

In [15]:
df.iloc[0:21,7].idxmin()

11

In [16]:
df.iloc[1:4,[0,2]]

   student_id  age
1           5   24
2           6   22
3           7   23

In [17]:
df.iloc[:,2].mean() #age av

21.380281690140844

In [18]:
df.iloc[:,2].value_counts()

21    76
19    72
20    68
22    65
23    60
25    60
18    52
24    44
Name: age, dtype: int64

In [19]:
df.iloc[:,1].value_counts()

Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: location, dtype: int64

In [20]:
df.iloc[:,1].value_counts().idxmax()

'Tokyo'

In [21]:
df.loc[0]

student_id             4
location          Sydney
age                   24
sql_marks             95
excel_marks           99
python_marks          87
power_bi_marks        82
english_marks         75
Name: 0, dtype: object

In [22]:
df.loc[0,"student_id"]

4

In [24]:
df.loc[0,["student_id","age"]]

student_id     4
age           24
Name: 0, dtype: object

In [25]:
df.loc[0:3,["student_id","age"]]

   student_id  age
0           4   24
1           5   24
2           6   22
3           7   23

In [26]:
df.loc[[10,20],["student_id","age"]]

    student_id  age
10          14   20
20          24   20

In [28]:
df.loc[df["age"]>23]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
8,12,Melbourne,24,80,95,87,90,94
11,15,Paris,24,94,93,87,80,71
13,17,Tokyo,25,82,75,77,78,85
...,...,...,...,...,...,...,...,...
485,489,Los Angeles,24,70,89,81,91,70
487,491,Melbourne,25,75,77,82,99,83
489,493,Los Angeles,24,94,74,80,92,95
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84

In [30]:
df.loc[df["age"]>23].shape

(104, 8)

In [31]:
df[df["age"]>23]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
8,12,Melbourne,24,80,95,87,90,94
11,15,Paris,24,94,93,87,80,71
13,17,Tokyo,25,82,75,77,78,85
...,...,...,...,...,...,...,...,...
485,489,Los Angeles,24,70,89,81,91,70
487,491,Melbourne,25,75,77,82,99,83
489,493,Los Angeles,24,94,74,80,92,95
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84

In [33]:
df[df["python_marks"]>95]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
2,6,Berlin,22,72,70,99,79,77
6,10,Tokyo,18,77,87,100,98,93
9,13,London,19,97,80,96,97,86
14,18,Melbourne,19,89,76,96,93,71
18,22,Los Angeles,22,83,73,100,75,85
...,...,...,...,...,...,...,...,...
460,464,New York,25,96,76,97,75,84
469,473,Los Angeles,23,76,89,98,80,94
472,476,Melbourne,20,95,82,96,93,70
481,485,Paris,21,89,98,96,83,79
492,496,New York,23,71,92,98,78,88

In [35]:
df[df["python_marks"]>95].shape[0]/df.shape[0] *100

16.901408450704224

In [40]:
df.sort_values(by="age")

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
195,199,Tokyo,18,89,97,74,74,76
88,92,Paris,18,98,100,71,86,77
325,329,Sydney,18,98,95,82,77,76
151,155,Toronto,18,80,89,90,77,97
156,160,Tokyo,18,80,86,77,96,95
...,...,...,...,...,...,...,...,...
106,110,New York,25,79,96,96,92,78
460,464,New York,25,96,76,97,75,84
326,330,Sydney,25,99,79,97,85,80
157,161,Paris,25,91,93,96,93,75
391,395,New York,25,70,100,79,78,74

In [42]:
df.columns

Index(['student_id', 'location', 'age', 'sql_marks', 'excel_marks',
       'python_marks', 'power_bi_marks', 'english_marks'],
      dtype='object')

In [46]:
df[(df["age"]>=22)&(df["age"]<=24)].shape

(169, 8)

In [56]:
a=df[(df["sql_marks"]>90)&(df["excel_marks"]>90)]
a

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
11,15,Paris,24,94,93,87,80,71
21,25,Paris,20,92,98,94,74,77
33,37,Tokyo,23,98,94,77,83,92
34,38,Berlin,21,100,95,78,73,77
47,51,London,23,96,96,71,74,100
55,59,New York,21,91,98,95,88,72
56,60,New York,19,95,94,94,83,78
77,81,Melbourne,22,93,98,79,87,88
87,91,London,21,100,95,81,86,70
88,92,Paris,18,98,100,71,86,77
103,107,New York,24,94,92,90,98,85
116,120,Toronto,20,98,100,87,90,82
118,122,Sydney,24,95,92,72,95,86
134,138,London,18,92,91,77,75,88
153,157,Melbourne,23,97,99,70,91,90
157,161,Paris,25,91,93,96,93,75
170,174,Melbourne,25,93,100,100,95,96
185,189,Toronto,19,100,94,88,74,88
197,201,Melbourne,25,100,91,75,99,98
208,212,Sydney,23,98,95,88,95,72
274,278,Toronto,22,99,95,74,76,87
302,306,London,22,100,94,89,93,70
305,309,Melbourne,19,95,99,81,75,98
320,324,Tokyo,19,97,94,90,94,82
325,329,Sydney,18,98,95,82,77,76
349,353,Los Angeles,24,93,91,82,96,81
362,366,Sydney,19,91,92,90,94,96
364,368,Los Angeles,18,94,99,70,96,79
367,371,Tokyo,23,97,91,94,75,77
372,376,Sydney,23,100,93,76,85,94
382,386,New York,19,94,91,99,85,99
383,387,Tokyo,19,93,96,77,100,98
406,410,Tokyo,25,93,99,81,76,73
412,416,Paris,22,92,91,94,71,96
428,432,Sydney,18,93,99,73,82,89
435,439,Berlin,21,92,99,96,92,88
453,457,New York,22,96,91,74,87,93
461,465,Paris,22,94,100,83,82,83
495,499,Los Angeles,21,96,93,78,78,82

In [57]:
import pandas as pd
b=pd.DataFrame(a)

In [60]:
b.loc[:,['student_id','age']]

     student_id  age
0             4   24
1             5   24
11           15   24
21           25   20
33           37   23
34           38   21
47           51   23
55           59   21
56           60   19
77           81   22
87           91   21
88           92   18
103         107   24
116         120   20
118         122   24
134         138   18
153         157   23
157         161   25
170         174   25
185         189   19
197         201   25
208         212   23
274         278   22
302         306   22
305         309   19
320         324   19
325         329   18
349         353   24
362         366   19
364         368   18
367         371   23
372         376   23
382         386   19
383         387   19
406         410   25
412         416   22
428         432   18
435         439   21
453         457   22
461         465   22
495         499   21

In [61]:
df.replace("London","LON")

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [62]:
df.set_index('student_id')

,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
student_id,,,,,,,
4,Sydney,24,95,99,87,82,75
5,Tokyo,24,99,95,89,86,82
6,Berlin,22,72,70,99,79,77
7,London,23,97,90,74,72,85
8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...
496,New York,23,71,92,98,78,88
497,Los Angeles,20,90,100,90,78,73
498,Paris,22,78,80,78,71,70
499,Los Angeles,21,96,93,78,78,82
500,London,22,85,87,93,70,86

In [69]:
df.rename(columns={'location':'Location'},inplace=True)
df

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [75]:
df[df['age'].between(22,30)]

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88
494,498,Paris,22,78,80,78,71,70
496,500,London,22,85,87,93,70,86

In [74]:
df[df['country'].isin(['Berlin','New York'])]

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
2,6,Berlin,22,72,70,99,79,77
16,20,Berlin,25,92,87,81,79,98
19,23,New York,18,80,73,94,89,100
20,24,Berlin,20,74,85,96,95,75
25,29,Berlin,20,92,82,98,76,71
...,...,...,...,...,...,...,...,...
473,477,New York,23,91,90,75,88,85
479,483,New York,20,81,95,90,83,71
484,488,Berlin,21,88,94,94,77,81
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88

In [76]:
df[df['age'].between(22,30)]

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88
494,498,Paris,22,78,80,78,71,70
496,500,London,22,85,87,93,70,86

In [77]:
import numpy as np
df.loc[0,'country']=np.nan

In [78]:
df.isnull().sum()

student_id        0
country           1
age               0
sql_marks         0
excel_marks       0
python_marks      0
power_bi_marks    0
english_marks     0
dtype: int64

In [79]:
df

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,NaN,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [82]:
df.fillna({'country':df['country'].mode()},inplace=True)
df

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Los Angeles,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [83]:
df.duplicated().sum()

0

In [86]:
#df.drope_duplicates()

In [87]:
df['pythonstatus']=df['python_marks'].map(lambda x:'pass'if x>60 else 'fail') #wecan use npwhere

In [88]:
df['pythonstatus']

0      pass
1      pass
2      pass
3      pass
4      pass
       ...
492    pass
493    pass
494    pass
495    pass
496    pass
Name: pythonstatus, Length: 497, dtype: object

In [89]:
df['pythonstatus'].value_counts

<bound method IndexOpsMixin.value_counts of 0      pass
1      pass
2      pass
3      pass
4      pass
       ...
492    pass
493    pass
494    pass
495    pass
496    pass
Name: pythonstatus, Length: 497, dtype: object>

In [91]:
locationgroup=df.groupby('country')
locationgroup

In [94]:
locationgroup.mean()

,student_id,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
country,,,,,,,
Berlin,220.942308,21.711538,82.230769,84.634615,85.653846,85.134615,82.480769
London,263.456522,21.478261,87.152174,85.673913,85.521739,83.695652,85.760870
Los Angeles,277.934426,21.459016,83.868852,85.704918,85.557377,83.983607,84.245902
Melbourne,258.293103,21.362069,84.965517,86.672414,83.637931,84.551724,85.568966
New York,251.245614,21.666667,85.175439,84.842105,86.771930,85.385965,84.947368
Paris,248.000000,20.927273,83.127273,85.636364,85.381818,84.054545,84.745455
Sydney,258.326923,21.250000,86.480769,85.250000,84.230769,85.192308,84.403846
Tokyo,232.950000,21.400000,84.650000,85.983333,86.033333,86.033333,84.766667
Toronto,255.892857,21.178571,84.732143,83.946429,85.642857,82.732143,86.500000

In [95]:
locationgroup['python_marks'].mean()

country
Berlin         85.653846
London         85.521739
Los Angeles    85.557377
Melbourne      83.637931
New York       86.771930
Paris          85.381818
Sydney         84.230769
Tokyo          86.033333
Toronto        85.642857
Name: python_marks, dtype: float64

In [100]:
locationgroup['python_marks'].max()['Paris']

100

In [101]:
locationgroup['python_marks'].idxmax()['Paris']

264

In [102]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "cars24data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "amanrajput16/used-car-price-data-from-cars24",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Temp\ipykernel_17592\4191626381.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/amanrajput16/used-car-price-data-from-cars24?dataset_version_number=1&file_name=cars24data.csv...

100%|████████████████████████████████████████████████████████████████████████████████| 111k/111k [00:00<00:00, 184kB/s]

First 5 records:                             Model Name    Price  Manufacturing_year  \
0                2017 Maruti Swift VXI   561000                2017
1  2016 Maruti Baleno DELTA PETROL 1.2   498000                2016
2                2020 Maruti Swift VXI   577000                2020
3       2022 Maruti Ertiga VXI AT SHVS  1084000                2022
4                2019 Maruti Dzire VXI   603000                2019

   Engine capacity Spare key Transmission  KM driven  Ownership Fuel type  \
0             1197        No       Manual      25847          2    Petrol
1             1197       Yes       Manual      55511          2    Petrol
2             1197        No       Manual      47110          1    Petrol
3             1462       Yes    Automatic      35378          1    Petrol
4             1197       Yes       Manual      91856          1    Petrol

   Imperfections  Repainted Parts
0              6                2
1             12                1
2              4                2
3              2                3
4              3                2

In [103]:
df.head()

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
0,2017 Maruti Swift VXI,561000,2017,1197,No,Manual,25847,2,Petrol,6,2
1,2016 Maruti Baleno DELTA PETROL 1.2,498000,2016,1197,Yes,Manual,55511,2,Petrol,12,1
2,2020 Maruti Swift VXI,577000,2020,1197,No,Manual,47110,1,Petrol,4,2
3,2022 Maruti Ertiga VXI AT SHVS,1084000,2022,1462,Yes,Automatic,35378,1,Petrol,2,3
4,2019 Maruti Dzire VXI,603000,2019,1197,Yes,Manual,91856,1,Petrol,3,2

In [104]:
import pandas as pd
import numpy as np

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Model Name          1445 non-null   object
 1   Price               1445 non-null   int64
 2   Manufacturing_year  1445 non-null   int64
 3   Engine capacity     1445 non-null   int64
 4   Spare key           1445 non-null   object
 5   Transmission        1445 non-null   object
 6   KM driven           1445 non-null   int64
 7   Ownership           1445 non-null   int64
 8   Fuel type           1445 non-null   object
 9   Imperfections       1445 non-null   int64
 10  Repainted Parts     1445 non-null   int64
dtypes: int64(7), object(4)
memory usage: 124.3+ KB

In [107]:
df.describe()

,Price,Manufacturing_year,Engine capacity,KM driven,Ownership,Imperfections,Repainted Parts
count,1.445000e+03,1445.000000,1445.000000,1445.000000,1445.000000,1445.000000,1445.000000
mean,5.263543e+05,2017.817301,1142.104498,50588.903114,1.285121,9.597232,3.228374
std,1.963696e+05,2.986554,169.020818,27339.562631,0.489877,8.398637,3.364578
min,1.390000e+05,2010.000000,796.000000,1207.000000,1.000000,0.000000,0.000000
25%,3.900000e+05,2016.000000,998.000000,28803.000000,1.000000,3.000000,0.000000
50%,5.010000e+05,2018.000000,1197.000000,47849.000000,1.000000,8.000000,2.000000
75%,6.310000e+05,2020.000000,1197.000000,70337.000000,2.000000,14.000000,5.000000
max,1.599000e+06,2023.000000,1462.000000,124716.000000,3.000000,43.000000,27.000000

In [109]:
df.isnull().sum()

Model Name            0
Price                 0
Manufacturing_year    0
Engine capacity       0
Spare key             0
Transmission          0
KM driven             0
Ownership             0
Fuel type             0
Imperfections         0
Repainted Parts       0
dtype: int64

In [113]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [114]:
df['Manufacturing_year'].unique()

array([2017, 2016, 2020, 2022, 2019, 2014, 2018, 2023, 2021, 2012, 2011,
       2015, 2013, 2010], dtype=int64)

In [115]:
df['Fuel type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [116]:
df['Transmission'].value_counts()

Manual       1073
Automatic     372
Name: Transmission, dtype: int64

In [120]:
df['Model Name'].value_counts()

2015 Maruti Wagon R 1.0 VXI            16
2021 Maruti Baleno DELTA PETROL 1.2    14
2016 Maruti Swift VXI                  14
2014 Maruti Swift VXI                  14
2017 Maruti Baleno DELTA PETROL 1.2    14
                                       ..
2022 Maruti XL6 ALPHA PLUS MT           1
2022 Maruti Eeco 5 STR STD(O)           1
2022 Maruti New Wagon-R LXI 1.0         1
2013 Maruti Ertiga VXI CNG              1
2017 Maruti Ciaz S 1.4 MT PETROL        1
Name: Model Name, Length: 573, dtype: int64

In [124]:
print(df['Price'].median()) #for price
print(df['Price'].max())
print(df['Price'].mean())

501000.0
1599000
526354.3252595155

In [126]:
df.shape[0] #car nu

1445

In [127]:
df['Fuel type'].unique()  #uniqe

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [128]:
df['Transmission'].mode() #mode transmi

0    Manual
Name: Transmission, dtype: object

In [129]:
print(df['KM driven'].mean()) #avr km

50588.903114186855

In [132]:
print("summary of price")
print("max price is ",df['Price'].max())
print("min price is ",df['Price'].min())
print("average price is ",df['Price'].mean())
print(df['Price'].describe())

summary of price
max price is  1599000
min price is  139000
average price is  526354.3252595155
count    1.445000e+03
mean     5.263543e+05
std      1.963696e+05
min      1.390000e+05
25%      3.900000e+05
50%      5.010000e+05
75%      6.310000e+05
max      1.599000e+06
Name: Price, dtype: float64

In [139]:
print("commen fuel type is",df['Fuel type'].mode()[0])
print("commen Transmission   type is",df['Transmission'].mode()[0])

commen fuel type is Petrol
commen Transmission   type is Manual

In [140]:
print("summary of KM driven")
print("max KM driven ",df['KM driven'].max())
print("min KM drivenis ",df['KM driven'].min())
print("average KM driven is ",df['KM driven'].mean())

summary of KM driven
max KM driven  124716
min KM drivenis  1207
average KM driven is  50588.903114186855

In [147]:
a=df.loc[:,['Fuel type','Price']]
a

     Fuel type    Price
0       Petrol   561000
1       Petrol   498000
2       Petrol   577000
3       Petrol  1084000
4       Petrol   603000
...        ...      ...
1440    Petrol   862000
1441    Petrol   507000
1442    Petrol   554000
1443    Petrol   557000
1444    Petrol   256000

[1445 rows x 2 columns]

In [148]:
fuelprice=df.groupby('Fuel type')['Price'].mean()
fuelprice

Fuel type
CNG       475807.339450
Diesel    589111.111111
Petrol    527138.449367
Name: Price, dtype: float64

In [152]:
nameprice=df.groupby('Model Name')['Price'].mean()
nameprice

Model Name
2010 Maruti A Star LXI           2.080000e+05
2011 Maruti Alto K10 VXI         1.773750e+05
2011 Maruti Ritz LXI             1.840000e+05
2011 Maruti Ritz VDI             3.620000e+05
2011 Maruti Ritz VXI             1.820000e+05
                                     ...
2023 Maruti S PRESSO VXI+        5.245000e+05
2023 Maruti Swift LXI            5.590000e+05
2023 Maruti Swift VXI            6.736667e+05
2023 Maruti XL6 ALPHA PLUS MT    1.228000e+06
2023 Maruti XL6 ZETA CNG         1.226500e+06
Name: Price, Length: 573, dtype: float64

In [154]:
Transmissionprice=df.groupby('Transmission')['Price'].mean()
Transmissionprice

Transmission
Automatic    601338.709677
Manual       500357.875116
Name: Price, dtype: float64

In [155]:
Ownershipprice=df.groupby('Ownership')['Price'].mean()
Ownershipprice

Ownership
1    547910.292729
2    474272.222222
3    369500.000000
Name: Price, dtype: float64

In [157]:
Manufacturing_yearp=df.groupby('Manufacturing_year')['Price'].mean()
Manufacturing_yearp

Manufacturing_year
2010    208000.000000
2011    238285.714286
2012    317717.948718
2013    344912.280702
2014    359078.431373
2015    420261.363636
2016    474853.146853
2017    477931.192661
2018    548111.801242
2019    561733.333333
2020    583637.681159
2021    636503.759398
2022    721184.000000
2023    775774.193548
Name: Price, dtype: float64

In [159]:
Manufacturing_yearpm=df.groupby('Manufacturing_year')['Price'].mean().idxmax()
Manufacturing_yearpm

2023