In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("henilj7/iphone-purchase-records")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/henilj7/iphone-purchase-records/1.archive...

100%|██████████| 1.71k/1.71k [00:00<00:00, 2.96MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/henilj7/iphone-purchase-records/versions/1

In [3]:
import os

os.listdir(path)

['iphone_purchase_records.csv']

In [4]:
import os

files = os.listdir(path)
print(files)

['iphone_purchase_records.csv']

In [5]:
import pandas as pd
import os

file_path = os.path.join(path, "iphone_purchase_records.csv")
df = pd.read_csv(file_path)

df.head()

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

df.head()

   Gender  Age  Salary  Purchase Iphone
0       1   19   19000                0
1       1   35   20000                0
2       0   26   43000                0
3       0   27   57000                0
4       1   19   76000                0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB

In [9]:
X = df[['Gender', 'Age', 'Salary']]
y = df['Purchase Iphone']

print(X.head())
print(y.head())

   Gender  Age  Salary
0       1   19   19000
1       1   35   20000
2       0   26   43000
3       0   27   57000
4       1   19   76000
0    0
1    0
2    0
3    0
4    0
Name: Purchase Iphone, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (320, 3)
X_test : (80, 3)
y_train: (320,)
y_test : (80,)

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model = Sequential([
    Dense(4, activation='relu', input_shape=(3,)),   # Hidden
    Dense(1, activation='sigmoid')                   # Output
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [17]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 63ms/step - accuracy: 0.5312 - loss: 0.6463 - val_accuracy: 0.4531 - val_loss: 0.7452
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.5664 - loss: 0.6377 - val_accuracy: 0.5000 - val_loss: 0.7363
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5938 - loss: 0.6301 - val_accuracy: 0.5156 - val_loss: 0.7283
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6289 - loss: 0.6234 - val_accuracy: 0.5156 - val_loss: 0.7201
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6602 - loss: 0.6169 - val_accuracy: 0.5312 - val_loss: 0.7134
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6836 - loss: 0.6109 - val_accuracy: 0.5781 - val_loss: 0.7072
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7070 - loss: 0.6051 - val_accuracy: 0.5938 - val_loss: 0.7023
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7383 - loss: 0.5997 - val_accuracy: 0.6094 - val_loss: 0.6962
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7461 - loss: 0.5943 - val_accuracy: 0.6250 - val_loss: 0.6908
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7617 - loss: 0.5891 - val_accuracy: 0.6250 - val_loss: 0.6858
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.7695 - loss: 0.5840 - val_accuracy: 0.6406 - val_loss: 0.6812
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.7773 - loss: 0.5789 - val_accuracy: 0.6562 - val_loss: 0.6773
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7812 - loss: 0.5741 - val_accuracy: 0.6719 - val_loss: 0.6730
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8008 - loss: 0.5693 - val_accuracy: 0.7188 - val_loss: 0.6694
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8164 - loss: 0.5647 - val_accuracy: 0.7188 - val_loss: 0.6658
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8203 - loss: 0.5601 - val_accuracy: 0.7656 - val_loss: 0.6621
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8242 - loss: 0.5556 - val_accuracy: 0.7656 - val_loss: 0.6586
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8398 - loss: 0.5512 - val_accuracy: 0.7812 - val_loss: 0.6544
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8438 - loss: 0.5467 - val_accuracy: 0.7812 - val_loss: 0.6517
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8477 - loss: 0.5424 - val_accuracy: 0.7812 - val_loss: 0.6485
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8438 - loss: 0.5381 - val_accuracy: 0.7969 - val_loss: 0.6450
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8477 - loss: 0.5336 - val_accuracy: 0.7969 - val_loss: 0.6414
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8477 - loss: 0.5293 - val_accuracy: 0.7969 - val_loss: 0.6388
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8516 - loss: 0.5253 - val_accuracy: 0.8125 - val_loss: 0.6358
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8633 - loss: 0.5210 - val_accuracy: 0.8281 - val_loss: 0.6336
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8672 - loss: 0.5167 - val_accuracy: 0.8281 - val_loss: 0.6304
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8672 - loss: 0.5127 - val_accuracy: 0.8281 - val_loss: 0.6269
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8789 - loss: 0.5086 - val_accuracy: 0.8281 - val_loss: 0.6239
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8789 - loss: 0.5043 - val_accuracy: 0.8438 - val_loss: 0.6220
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8828 - loss: 0.5004 - val_accuracy: 0.8438 - val_loss: 0.6199
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8867 - loss: 0.4962 - val_accuracy: 0.8438 - val_loss: 0.6173
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8906 - loss: 0.4925 - val_accuracy: 0.8438 - val_loss: 0.6149
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8945 - loss: 0.4886 - val_accuracy: 0.8438 - val_loss: 0.6131
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8984 - loss: 0.4847 - val_accuracy: 0.8594 - val_loss: 0.6104
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8984 - loss: 0.4810 - val_accuracy: 0.8750 - val_loss: 0.6071
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8984 - loss: 0.4773 - val_accuracy: 0.8750 - val_loss: 0.6059
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.4737 - val_accuracy: 0.8750 - val_loss: 0.6030
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8984 - loss: 0.4703 - val_accuracy: 0.8594 - val_loss: 0.6008
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8945 - loss: 0.4669 - val_accuracy: 0.8594 - val_loss: 0.6002
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8984 - loss: 0.4632 - val_accuracy: 0.8438 - val_loss: 0.5982
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.8984 - loss: 0.4598 - val_accuracy: 0.8438 - val_loss: 0.5956
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8984 - loss: 0.4565 - val_accuracy: 0.8438 - val_loss: 0.5938
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9023 - loss: 0.4532 - val_accuracy: 0.8438 - val_loss: 0.5924
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9023 - loss: 0.4501 - val_accuracy: 0.8438 - val_loss: 0.5902
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9023 - loss: 0.4469 - val_accuracy: 0.8438 - val_loss: 0.5878
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9023 - loss: 0.4436 - val_accuracy: 0.8438 - val_loss: 0.5866
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9102 - loss: 0.4406 - val_accuracy: 0.8594 - val_loss: 0.5851
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9141 - loss: 0.4376 - val_accuracy: 0.8438 - val_loss: 0.5825
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9141 - loss: 0.4346 - val_accuracy: 0.8594 - val_loss: 0.5823
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9141 - loss: 0.4315 - val_accuracy: 0.8594 - val_loss: 0.5789

In [18]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9000 - loss: 0.4819
Test Loss: 0.48186761140823364
Test Accuracy: 0.8999999761581421

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(2, activation='relu', input_shape=(3,)),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - accuracy: 0.3164 - loss: 1.0009 - val_accuracy: 0.2031 - val_loss: 1.2325
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3359 - loss: 0.9746 - val_accuracy: 0.2031 - val_loss: 1.1972
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.3320 - loss: 0.9500 - val_accuracy: 0.2188 - val_loss: 1.1640
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3242 - loss: 0.9272 - val_accuracy: 0.2344 - val_loss: 1.1333
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3281 - loss: 0.9056 - val_accuracy: 0.2344 - val_loss: 1.1048
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3164 - loss: 0.8862 - val_accuracy: 0.2344 - val_loss: 1.0769
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3125 - loss: 0.8666 - val_accuracy: 0.2344 - val_loss: 1.0520
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3164 - loss: 0.8489 - val_accuracy: 0.2500 - val_loss: 1.0290
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3164 - loss: 0.8327 - val_accuracy: 0.2656 - val_loss: 1.0061
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3281 - loss: 0.8169 - val_accuracy: 0.2500 - val_loss: 0.9848
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3320 - loss: 0.8026 - val_accuracy: 0.2344 - val_loss: 0.9641
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3359 - loss: 0.7880 - val_accuracy: 0.2344 - val_loss: 0.9469
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3477 - loss: 0.7763 - val_accuracy: 0.2656 - val_loss: 0.9279
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3945 - loss: 0.7640 - val_accuracy: 0.2969 - val_loss: 0.9114
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4219 - loss: 0.7532 - val_accuracy: 0.3438 - val_loss: 0.8961
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4492 - loss: 0.7438 - val_accuracy: 0.4062 - val_loss: 0.8808
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4648 - loss: 0.7339 - val_accuracy: 0.4844 - val_loss: 0.8678
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4922 - loss: 0.7254 - val_accuracy: 0.4844 - val_loss: 0.8547
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5391 - loss: 0.7172 - val_accuracy: 0.5156 - val_loss: 0.8424
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5820 - loss: 0.7093 - val_accuracy: 0.5156 - val_loss: 0.8308
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6133 - loss: 0.7019 - val_accuracy: 0.5312 - val_loss: 0.8198
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6211 - loss: 0.6949 - val_accuracy: 0.5312 - val_loss: 0.8097
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6250 - loss: 0.6885 - val_accuracy: 0.5312 - val_loss: 0.8001
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6172 - loss: 0.6821 - val_accuracy: 0.5781 - val_loss: 0.7907
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6211 - loss: 0.6759 - val_accuracy: 0.5781 - val_loss: 0.7824
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6702 - val_accuracy: 0.5938 - val_loss: 0.7741
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6289 - loss: 0.6648 - val_accuracy: 0.5938 - val_loss: 0.7661
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6328 - loss: 0.6598 - val_accuracy: 0.5938 - val_loss: 0.7576
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6367 - loss: 0.6544 - val_accuracy: 0.5938 - val_loss: 0.7511
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6445 - loss: 0.6499 - val_accuracy: 0.5938 - val_loss: 0.7443
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6602 - loss: 0.6454 - val_accuracy: 0.6094 - val_loss: 0.7373
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6680 - loss: 0.6411 - val_accuracy: 0.6250 - val_loss: 0.7306
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6758 - loss: 0.6368 - val_accuracy: 0.6250 - val_loss: 0.7246
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6875 - loss: 0.6327 - val_accuracy: 0.6250 - val_loss: 0.7188
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6914 - loss: 0.6287 - val_accuracy: 0.6250 - val_loss: 0.7134
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6953 - loss: 0.6248 - val_accuracy: 0.6250 - val_loss: 0.7083
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6992 - loss: 0.6212 - val_accuracy: 0.6250 - val_loss: 0.7033
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6992 - loss: 0.6176 - val_accuracy: 0.6406 - val_loss: 0.6986
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7031 - loss: 0.6141 - val_accuracy: 0.6406 - val_loss: 0.6942
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7031 - loss: 0.6108 - val_accuracy: 0.6406 - val_loss: 0.6897
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7031 - loss: 0.6074 - val_accuracy: 0.6406 - val_loss: 0.6858
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7070 - loss: 0.6043 - val_accuracy: 0.6406 - val_loss: 0.6818
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7109 - loss: 0.6013 - val_accuracy: 0.6406 - val_loss: 0.6780
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7148 - loss: 0.5981 - val_accuracy: 0.6406 - val_loss: 0.6745
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7148 - loss: 0.5953 - val_accuracy: 0.6406 - val_loss: 0.6713
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7188 - loss: 0.5925 - val_accuracy: 0.6562 - val_loss: 0.6680
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7188 - loss: 0.5900 - val_accuracy: 0.6562 - val_loss: 0.6645
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7188 - loss: 0.5872 - val_accuracy: 0.6562 - val_loss: 0.6617
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7227 - loss: 0.5848 - val_accuracy: 0.6406 - val_loss: 0.6591
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7227 - loss: 0.5823 - val_accuracy: 0.6406 - val_loss: 0.6562
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6750 - loss: 0.6282
Test Accuracy: 0.675000011920929

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(6, activation='relu', input_shape=(3,)),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - accuracy: 0.6562 - loss: 0.7195 - val_accuracy: 0.7969 - val_loss: 0.6046
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.6680 - loss: 0.6898 - val_accuracy: 0.7969 - val_loss: 0.5910
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6719 - loss: 0.6631 - val_accuracy: 0.7812 - val_loss: 0.5789
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6758 - loss: 0.6389 - val_accuracy: 0.7812 - val_loss: 0.5678
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6797 - loss: 0.6173 - val_accuracy: 0.8125 - val_loss: 0.5580
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7070 - loss: 0.5967 - val_accuracy: 0.8125 - val_loss: 0.5491
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7422 - loss: 0.5779 - val_accuracy: 0.7969 - val_loss: 0.5419
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7422 - loss: 0.5611 - val_accuracy: 0.7812 - val_loss: 0.5347
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7656 - loss: 0.5457 - val_accuracy: 0.7969 - val_loss: 0.5288
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7930 - loss: 0.5309 - val_accuracy: 0.7969 - val_loss: 0.5229
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7930 - loss: 0.5176 - val_accuracy: 0.7969 - val_loss: 0.5175
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7930 - loss: 0.5056 - val_accuracy: 0.7969 - val_loss: 0.5123
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7930 - loss: 0.4951 - val_accuracy: 0.7969 - val_loss: 0.5088
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7930 - loss: 0.4837 - val_accuracy: 0.8125 - val_loss: 0.5038
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7969 - loss: 0.4741 - val_accuracy: 0.8125 - val_loss: 0.4997
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8086 - loss: 0.4646 - val_accuracy: 0.8125 - val_loss: 0.4953
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8086 - loss: 0.4562 - val_accuracy: 0.8125 - val_loss: 0.4922
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4481 - val_accuracy: 0.7969 - val_loss: 0.4876
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4398 - val_accuracy: 0.7969 - val_loss: 0.4837
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.4323 - val_accuracy: 0.7969 - val_loss: 0.4802
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.4255 - val_accuracy: 0.7812 - val_loss: 0.4770
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8359 - loss: 0.4187 - val_accuracy: 0.7969 - val_loss: 0.4730
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8359 - loss: 0.4126 - val_accuracy: 0.7812 - val_loss: 0.4716
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8359 - loss: 0.4065 - val_accuracy: 0.7969 - val_loss: 0.4677
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8398 - loss: 0.4007 - val_accuracy: 0.7969 - val_loss: 0.4651
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8398 - loss: 0.3954 - val_accuracy: 0.7969 - val_loss: 0.4625
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8398 - loss: 0.3901 - val_accuracy: 0.7969 - val_loss: 0.4609
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8477 - loss: 0.3854 - val_accuracy: 0.7969 - val_loss: 0.4598
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8477 - loss: 0.3811 - val_accuracy: 0.7812 - val_loss: 0.4588
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8477 - loss: 0.3768 - val_accuracy: 0.7969 - val_loss: 0.4559
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8477 - loss: 0.3728 - val_accuracy: 0.7969 - val_loss: 0.4546
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8516 - loss: 0.3689 - val_accuracy: 0.7969 - val_loss: 0.4524
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8477 - loss: 0.3657 - val_accuracy: 0.7812 - val_loss: 0.4523
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3622 - val_accuracy: 0.7969 - val_loss: 0.4494
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3590 - val_accuracy: 0.7812 - val_loss: 0.4487
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3560 - val_accuracy: 0.8125 - val_loss: 0.4468
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3533 - val_accuracy: 0.8125 - val_loss: 0.4455
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3507 - val_accuracy: 0.8125 - val_loss: 0.4436
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3483 - val_accuracy: 0.7969 - val_loss: 0.4432
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3456 - val_accuracy: 0.7969 - val_loss: 0.4435
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3434 - val_accuracy: 0.7969 - val_loss: 0.4426
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3413 - val_accuracy: 0.7969 - val_loss: 0.4410
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3394 - val_accuracy: 0.7969 - val_loss: 0.4400
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3373 - val_accuracy: 0.7969 - val_loss: 0.4404
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3356 - val_accuracy: 0.7969 - val_loss: 0.4401
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3339 - val_accuracy: 0.7969 - val_loss: 0.4402
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3323 - val_accuracy: 0.7969 - val_loss: 0.4407
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3305 - val_accuracy: 0.7969 - val_loss: 0.4394
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3290 - val_accuracy: 0.7969 - val_loss: 0.4392
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3279 - val_accuracy: 0.7969 - val_loss: 0.4383
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8125 - loss: 0.4161
Test Accuracy: 0.8125

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(6, activation='relu', input_shape=(3,)),  # Hidden Layer 1
    Dense(4, activation='relu'),                    # Hidden Layer 2
    Dense(1, activation='sigmoid')                  # Output Layer
])


model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.7148 - loss: 0.6298 - val_accuracy: 0.6250 - val_loss: 0.6707
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7773 - loss: 0.6112 - val_accuracy: 0.7031 - val_loss: 0.6532
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8086 - loss: 0.5960 - val_accuracy: 0.7188 - val_loss: 0.6381
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8242 - loss: 0.5807 - val_accuracy: 0.7500 - val_loss: 0.6247
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8359 - loss: 0.5660 - val_accuracy: 0.7344 - val_loss: 0.6115
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8359 - loss: 0.5518 - val_accuracy: 0.7344 - val_loss: 0.5989
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.5375 - val_accuracy: 0.7344 - val_loss: 0.5904
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.5244 - val_accuracy: 0.7500 - val_loss: 0.5830
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.5105 - val_accuracy: 0.7656 - val_loss: 0.5764
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.4983 - val_accuracy: 0.7656 - val_loss: 0.5689
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8633 - loss: 0.4860 - val_accuracy: 0.7656 - val_loss: 0.5623
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.4751 - val_accuracy: 0.7812 - val_loss: 0.5572
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.4648 - val_accuracy: 0.7969 - val_loss: 0.5519
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.4548 - val_accuracy: 0.7969 - val_loss: 0.5462
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.4459 - val_accuracy: 0.7969 - val_loss: 0.5410
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.4370 - val_accuracy: 0.7969 - val_loss: 0.5360
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.4290 - val_accuracy: 0.8125 - val_loss: 0.5297
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.4204 - val_accuracy: 0.8125 - val_loss: 0.5257
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.4116 - val_accuracy: 0.8438 - val_loss: 0.5175
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8828 - loss: 0.4008 - val_accuracy: 0.8438 - val_loss: 0.5096
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3889 - val_accuracy: 0.8438 - val_loss: 0.4983
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3745 - val_accuracy: 0.8281 - val_loss: 0.4879
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3590 - val_accuracy: 0.8281 - val_loss: 0.4760
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8906 - loss: 0.3439 - val_accuracy: 0.8281 - val_loss: 0.4578
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8984 - loss: 0.3269 - val_accuracy: 0.8281 - val_loss: 0.4420
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9062 - loss: 0.3117 - val_accuracy: 0.8281 - val_loss: 0.4291
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9102 - loss: 0.2987 - val_accuracy: 0.8438 - val_loss: 0.4201
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9102 - loss: 0.2879 - val_accuracy: 0.8438 - val_loss: 0.4142
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9102 - loss: 0.2793 - val_accuracy: 0.8438 - val_loss: 0.4055
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9102 - loss: 0.2720 - val_accuracy: 0.8438 - val_loss: 0.4016
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9102 - loss: 0.2657 - val_accuracy: 0.8438 - val_loss: 0.3997
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.2607 - val_accuracy: 0.8438 - val_loss: 0.3967
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9102 - loss: 0.2553 - val_accuracy: 0.8438 - val_loss: 0.3966
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9141 - loss: 0.2511 - val_accuracy: 0.8438 - val_loss: 0.3956
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9141 - loss: 0.2471 - val_accuracy: 0.8438 - val_loss: 0.3947
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2434 - val_accuracy: 0.8438 - val_loss: 0.3907
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2405 - val_accuracy: 0.8438 - val_loss: 0.3917
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9180 - loss: 0.2379 - val_accuracy: 0.8438 - val_loss: 0.3911
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2352 - val_accuracy: 0.8438 - val_loss: 0.3922
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2333 - val_accuracy: 0.8594 - val_loss: 0.3931
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2311 - val_accuracy: 0.8594 - val_loss: 0.3956
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2296 - val_accuracy: 0.8594 - val_loss: 0.3976
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2277 - val_accuracy: 0.8594 - val_loss: 0.3943
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2263 - val_accuracy: 0.8594 - val_loss: 0.3947
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2249 - val_accuracy: 0.8594 - val_loss: 0.3961
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9219 - loss: 0.2240 - val_accuracy: 0.8594 - val_loss: 0.3980
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2225 - val_accuracy: 0.8594 - val_loss: 0.3975
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2221 - val_accuracy: 0.8594 - val_loss: 0.3985
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2209 - val_accuracy: 0.8594 - val_loss: 0.3962
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2199 - val_accuracy: 0.8594 - val_loss: 0.3969

In [22]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9000 - loss: 0.2841
Test Accuracy: 0.8999999761581421

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(16, activation='relu', input_shape=(3,)),
    Dense(8, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [24]:
epochs=100

In [25]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.5156 - loss: 0.6908 - val_accuracy: 0.6094 - val_loss: 0.6741
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5703 - loss: 0.6711 - val_accuracy: 0.7188 - val_loss: 0.6549
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6094 - loss: 0.6535 - val_accuracy: 0.7500 - val_loss: 0.6369
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6172 - loss: 0.6318 - val_accuracy: 0.7500 - val_loss: 0.6116
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6172 - loss: 0.6045 - val_accuracy: 0.7500 - val_loss: 0.5786
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6172 - loss: 0.5784 - val_accuracy: 0.7500 - val_loss: 0.5442
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6211 - loss: 0.5506 - val_accuracy: 0.7500 - val_loss: 0.5132
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6250 - loss: 0.5235 - val_accuracy: 0.7500 - val_loss: 0.4799
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6250 - loss: 0.4964 - val_accuracy: 0.7500 - val_loss: 0.4468
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6328 - loss: 0.4723 - val_accuracy: 0.7812 - val_loss: 0.4231
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6289 - loss: 0.4519 - val_accuracy: 0.7812 - val_loss: 0.4030
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6367 - loss: 0.4356 - val_accuracy: 0.7969 - val_loss: 0.3861
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7891 - loss: 0.4217 - val_accuracy: 0.8125 - val_loss: 0.3727
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8320 - loss: 0.4094 - val_accuracy: 0.7969 - val_loss: 0.3627
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8398 - loss: 0.4006 - val_accuracy: 0.7969 - val_loss: 0.3542
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8398 - loss: 0.3921 - val_accuracy: 0.7969 - val_loss: 0.3446
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8438 - loss: 0.3844 - val_accuracy: 0.8125 - val_loss: 0.3375
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8516 - loss: 0.3775 - val_accuracy: 0.8281 - val_loss: 0.3286
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8633 - loss: 0.3693 - val_accuracy: 0.8281 - val_loss: 0.3245
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8828 - loss: 0.3593 - val_accuracy: 0.8281 - val_loss: 0.3161
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8984 - loss: 0.3506 - val_accuracy: 0.8438 - val_loss: 0.3102
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.3389 - val_accuracy: 0.8438 - val_loss: 0.3048
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.3288 - val_accuracy: 0.8438 - val_loss: 0.2998
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9141 - loss: 0.3185 - val_accuracy: 0.8438 - val_loss: 0.2958
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9062 - loss: 0.3096 - val_accuracy: 0.8438 - val_loss: 0.2918
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9219 - loss: 0.3001 - val_accuracy: 0.8438 - val_loss: 0.2911
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9219 - loss: 0.2912 - val_accuracy: 0.8438 - val_loss: 0.2900
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9180 - loss: 0.2825 - val_accuracy: 0.8438 - val_loss: 0.2877
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2751 - val_accuracy: 0.8438 - val_loss: 0.2885
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2668 - val_accuracy: 0.8438 - val_loss: 0.2883
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2609 - val_accuracy: 0.8438 - val_loss: 0.2929
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2552 - val_accuracy: 0.8438 - val_loss: 0.2939
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2500 - val_accuracy: 0.8438 - val_loss: 0.2969
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9219 - loss: 0.2454 - val_accuracy: 0.8438 - val_loss: 0.3015
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2411 - val_accuracy: 0.8438 - val_loss: 0.3039
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2381 - val_accuracy: 0.8594 - val_loss: 0.3039
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2347 - val_accuracy: 0.8594 - val_loss: 0.3073
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2325 - val_accuracy: 0.8594 - val_loss: 0.3116

In [26]:
from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.001)

model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [27]:
batch_size=16

In [28]:
from tensorflow.keras.layers import Dropout

model = Sequential([
    Dense(16, activation='relu', input_shape=(3,)),
    Dropout(0.2),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [29]:
X = df[['Age','Salary']]
y = df['Purchase Iphone']

In [30]:
Dense(8, activation='relu', input_shape=(2,))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [32]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [35]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9125 - loss: 0.2403
Final Test Loss: 0.2403322011232376
Final Test Accuracy: 0.9125000238418579

In [34]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5664 - loss: 0.6737 - val_accuracy: 0.5469 - val_loss: 0.6888
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7266 - loss: 0.6176 - val_accuracy: 0.7188 - val_loss: 0.6436
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7617 - loss: 0.5878 - val_accuracy: 0.7812 - val_loss: 0.6018
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.5596 - val_accuracy: 0.7812 - val_loss: 0.5683
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.5084 - val_accuracy: 0.7969 - val_loss: 0.5377
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.4874 - val_accuracy: 0.8125 - val_loss: 0.5107
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.4570 - val_accuracy: 0.8438 - val_loss: 0.4879
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.4305 - val_accuracy: 0.8438 - val_loss: 0.4665
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8477 - loss: 0.4153 - val_accuracy: 0.8438 - val_loss: 0.4513
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8477 - loss: 0.3994 - val_accuracy: 0.8438 - val_loss: 0.4411
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8398 - loss: 0.3958 - val_accuracy: 0.8438 - val_loss: 0.4301
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8945 - loss: 0.3689 - val_accuracy: 0.8438 - val_loss: 0.4216
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8789 - loss: 0.3410 - val_accuracy: 0.8438 - val_loss: 0.4148
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8633 - loss: 0.3459 - val_accuracy: 0.8438 - val_loss: 0.4080
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8672 - loss: 0.3262 - val_accuracy: 0.8438 - val_loss: 0.4052
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.3246 - val_accuracy: 0.8438 - val_loss: 0.4078
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8984 - loss: 0.3093 - val_accuracy: 0.8438 - val_loss: 0.4079
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8828 - loss: 0.3114 - val_accuracy: 0.8438 - val_loss: 0.4075
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3077 - val_accuracy: 0.8438 - val_loss: 0.4066
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8828 - loss: 0.2962 - val_accuracy: 0.8438 - val_loss: 0.4057
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8867 - loss: 0.2979 - val_accuracy: 0.8438 - val_loss: 0.4061
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8711 - loss: 0.2865 - val_accuracy: 0.8438 - val_loss: 0.4071
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2807 - val_accuracy: 0.8438 - val_loss: 0.4052
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2803 - val_accuracy: 0.8438 - val_loss: 0.4089
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2765 - val_accuracy: 0.8438 - val_loss: 0.4083
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2690 - val_accuracy: 0.8438 - val_loss: 0.4106
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2927 - val_accuracy: 0.8594 - val_loss: 0.4097
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2560 - val_accuracy: 0.8594 - val_loss: 0.4122
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2539 - val_accuracy: 0.8438 - val_loss: 0.4115
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2685 - val_accuracy: 0.8438 - val_loss: 0.4154
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2751 - val_accuracy: 0.8438 - val_loss: 0.4135
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2460 - val_accuracy: 0.8594 - val_loss: 0.4170
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2615 - val_accuracy: 0.8594 - val_loss: 0.4178
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2366 - val_accuracy: 0.8438 - val_loss: 0.4191
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2533 - val_accuracy: 0.8438 - val_loss: 0.4151
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2409 - val_accuracy: 0.8438 - val_loss: 0.4194
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2347 - val_accuracy: 0.8594 - val_loss: 0.4207
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2491 - val_accuracy: 0.8594 - val_loss: 0.4223
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2491 - val_accuracy: 0.8594 - val_loss: 0.4247
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2724 - val_accuracy: 0.8594 - val_loss: 0.4230
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2330 - val_accuracy: 0.8594 - val_loss: 0.4234
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2350 - val_accuracy: 0.8594 - val_loss: 0.4230
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2573 - val_accuracy: 0.8594 - val_loss: 0.4205
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2483 - val_accuracy: 0.8594 - val_loss: 0.4221
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2570 - val_accuracy: 0.8594 - val_loss: 0.4178
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2408 - val_accuracy: 0.8594 - val_loss: 0.4164
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2260 - val_accuracy: 0.8594 - val_loss: 0.4162
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9180 - loss: 0.2368 - val_accuracy: 0.8594 - val_loss: 0.4184
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2320 - val_accuracy: 0.8594 - val_loss: 0.4232
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2458 - val_accuracy: 0.8594 - val_loss: 0.4224
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2336 - val_accuracy: 0.8594 - val_loss: 0.4244
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2477 - val_accuracy: 0.8594 - val_loss: 0.4234
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2444 - val_accuracy: 0.8594 - val_loss: 0.4197
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2587 - val_accuracy: 0.8594 - val_loss: 0.4209
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2489 - val_accuracy: 0.8594 - val_loss: 0.4202
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2351 - val_accuracy: 0.8750 - val_loss: 0.4145
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9219 - loss: 0.2013 - val_accuracy: 0.8750 - val_loss: 0.4168
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2662 - val_accuracy: 0.8750 - val_loss: 0.4151
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2304 - val_accuracy: 0.8750 - val_loss: 0.4151
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2520 - val_accuracy: 0.8750 - val_loss: 0.4112
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2349 - val_accuracy: 0.8750 - val_loss: 0.4052
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2249 - val_accuracy: 0.8750 - val_loss: 0.4040
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2563 - val_accuracy: 0.8750 - val_loss: 0.4080
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2548 - val_accuracy: 0.8750 - val_loss: 0.4059
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2325 - val_accuracy: 0.8750 - val_loss: 0.4077
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2315 - val_accuracy: 0.8750 - val_loss: 0.4056
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2375 - val_accuracy: 0.8750 - val_loss: 0.4085
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8789 - loss: 0.2486 - val_accuracy: 0.8750 - val_loss: 0.4113
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2426 - val_accuracy: 0.8750 - val_loss: 0.4163
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2493 - val_accuracy: 0.8594 - val_loss: 0.4186
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2524 - val_accuracy: 0.8594 - val_loss: 0.4146
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2562 - val_accuracy: 0.8594 - val_loss: 0.4139
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2128 - val_accuracy: 0.8750 - val_loss: 0.4081
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2252 - val_accuracy: 0.8750 - val_loss: 0.4082
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2221 - val_accuracy: 0.8750 - val_loss: 0.4131
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2418 - val_accuracy: 0.8594 - val_loss: 0.4140
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2305 - val_accuracy: 0.8594 - val_loss: 0.4128
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2316 - val_accuracy: 0.8594 - val_loss: 0.4084
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2246 - val_accuracy: 0.8594 - val_loss: 0.4154
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2448 - val_accuracy: 0.8594 - val_loss: 0.4123
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9297 - loss: 0.2296 - val_accuracy: 0.8594 - val_loss: 0.4166
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.2527 - val_accuracy: 0.8594 - val_loss: 0.4111
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2159 - val_accuracy: 0.8594 - val_loss: 0.4087
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2300 - val_accuracy: 0.8594 - val_loss: 0.4102
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2196 - val_accuracy: 0.8594 - val_loss: 0.4103
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2047 - val_accuracy: 0.8594 - val_loss: 0.4142
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2394 - val_accuracy: 0.8594 - val_loss: 0.4171
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9336 - loss: 0.2057 - val_accuracy: 0.8594 - val_loss: 0.4168
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2400 - val_accuracy: 0.8594 - val_loss: 0.4147
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2266 - val_accuracy: 0.8594 - val_loss: 0.4176
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2308 - val_accuracy: 0.8594 - val_loss: 0.4141
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2209 - val_accuracy: 0.8594 - val_loss: 0.4156
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.2175 - val_accuracy: 0.8594 - val_loss: 0.4195
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9258 - loss: 0.2254 - val_accuracy: 0.8594 - val_loss: 0.4192
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2363 - val_accuracy: 0.8594 - val_loss: 0.4183
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2416 - val_accuracy: 0.8594 - val_loss: 0.4182
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2161 - val_accuracy: 0.8594 - val_loss: 0.4179
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2173 - val_accuracy: 0.8594 - val_loss: 0.4172
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9258 - loss: 0.2027 - val_accuracy: 0.8594 - val_loss: 0.4180
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2236 - val_accuracy: 0.8594 - val_loss: 0.4168

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau


tf.keras.utils.set_random_seed(42)



model = Sequential([

    # Hidden Layer 1
    Dense(32, activation='relu', input_shape=(3,)),
    BatchNormalization(),
    Dropout(0.2),

    # Hidden Layer 2
    Dense(16, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    # Hidden Layer 3
    Dense(8, activation='relu'),

    # Output Layer
    Dense(1, activation='sigmoid')
])



optimizer = Adam(
    learning_rate=0.001
)

model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)



early_stop = EarlyStopping(
    monitor='val_loss',
    patience=15,
    restore_best_weights=True
)


reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=0.00001
)



history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=8,
    validation_split=0.2,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)


print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")


# Model Summary

model.summary()

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.3984 - loss: 1.0727 - val_accuracy: 0.4062 - val_loss: 0.7068 - learning_rate: 0.0010
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4258 - loss: 0.8235 - val_accuracy: 0.5156 - val_loss: 0.7044 - learning_rate: 0.0010
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6367 - loss: 0.6679 - val_accuracy: 0.6094 - val_loss: 0.6893 - learning_rate: 0.0010
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6445 - loss: 0.6147 - val_accuracy: 0.6719 - val_loss: 0.6585 - learning_rate: 0.0010
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7617 - loss: 0.5415 - val_accuracy: 0.7031 - val_loss: 0.6218 - learning_rate: 0.0010
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7969 - loss: 0.5041 - val_accuracy: 0.7656 - val_loss: 0.5797 - learning_rate: 0.0010
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7852 - loss: 0.4787 - val_accuracy: 0.8438 - val_loss: 0.5360 - learning_rate: 0.0010
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8281 - loss: 0.4429 - val_accuracy: 0.8594 - val_loss: 0.4974 - learning_rate: 0.0010
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8242 - loss: 0.4246 - val_accuracy: 0.8594 - val_loss: 0.4658 - learning_rate: 0.0010
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.4007 - val_accuracy: 0.8750 - val_loss: 0.4420 - learning_rate: 0.0010
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3958 - val_accuracy: 0.8750 - val_loss: 0.4197 - learning_rate: 0.0010
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.3614 - val_accuracy: 0.8750 - val_loss: 0.4070 - learning_rate: 0.0010
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3527 - val_accuracy: 0.8594 - val_loss: 0.3956 - learning_rate: 0.0010
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3719 - val_accuracy: 0.8750 - val_loss: 0.3920 - learning_rate: 0.0010
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3595 - val_accuracy: 0.8594 - val_loss: 0.3990 - learning_rate: 0.0010
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.3229 - val_accuracy: 0.8594 - val_loss: 0.3857 - learning_rate: 0.0010
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8711 - loss: 0.3225 - val_accuracy: 0.8750 - val_loss: 0.3841 - learning_rate: 0.0010
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3460 - val_accuracy: 0.8906 - val_loss: 0.3794 - learning_rate: 0.0010
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3428 - val_accuracy: 0.8906 - val_loss: 0.3820 - learning_rate: 0.0010
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.3135 - val_accuracy: 0.8594 - val_loss: 0.3904 - learning_rate: 0.0010
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.3246 - val_accuracy: 0.8906 - val_loss: 0.3951 - learning_rate: 0.0010
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3233 - val_accuracy: 0.8906 - val_loss: 0.3926 - learning_rate: 0.0010
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8945 - loss: 0.3116 - val_accuracy: 0.8594 - val_loss: 0.4033 - learning_rate: 0.0010
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.2825 - val_accuracy: 0.8594 - val_loss: 0.4044 - learning_rate: 5.0000e-04
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8633 - loss: 0.3012 - val_accuracy: 0.8594 - val_loss: 0.4055 - learning_rate: 5.0000e-04
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.2749 - val_accuracy: 0.8281 - val_loss: 0.4064 - learning_rate: 5.0000e-04
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2938 - val_accuracy: 0.8438 - val_loss: 0.4050 - learning_rate: 5.0000e-04
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2997 - val_accuracy: 0.8281 - val_loss: 0.4116 - learning_rate: 5.0000e-04
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2898 - val_accuracy: 0.8281 - val_loss: 0.4088 - learning_rate: 2.5000e-04
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9062 - loss: 0.2476 - val_accuracy: 0.8281 - val_loss: 0.4083 - learning_rate: 2.5000e-04
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8789 - loss: 0.2924 - val_accuracy: 0.8281 - val_loss: 0.4111 - learning_rate: 2.5000e-04
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2685 - val_accuracy: 0.8281 - val_loss: 0.4149 - learning_rate: 2.5000e-04
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.3236 - val_accuracy: 0.8594 - val_loss: 0.4109 - learning_rate: 2.5000e-04
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8625 - loss: 0.2938
========================
Final Test Loss: 0.29382044076919556
Final Test Accuracy: 0.862500011920929
========================

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,789 (10.90 KB)

 Trainable params: 897 (3.50 KB)

 Non-trainable params: 96 (384.00 B)

 Optimizer params: 1,796 (7.02 KB)

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


tf.keras.utils.set_random_seed(42)



model = Sequential([

    Dense(16, activation='relu', input_shape=(3,)),

    Dense(8, activation='relu'),

    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)



early_stop = EarlyStopping(
    monitor='val_loss',
    patience=20,
    restore_best_weights=True
)


history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=8,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)

print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")

model.summary()

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.3594 - loss: 0.7834 - val_accuracy: 0.4844 - val_loss: 0.7083
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4336 - loss: 0.7445 - val_accuracy: 0.5312 - val_loss: 0.6713
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5078 - loss: 0.7096 - val_accuracy: 0.6875 - val_loss: 0.6383
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6094 - loss: 0.6785 - val_accuracy: 0.7812 - val_loss: 0.6082
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6562 - loss: 0.6497 - val_accuracy: 0.8281 - val_loss: 0.5791
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6914 - loss: 0.6224 - val_accuracy: 0.7969 - val_loss: 0.5520
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6992 - loss: 0.5975 - val_accuracy: 0.7812 - val_loss: 0.5265
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7070 - loss: 0.5737 - val_accuracy: 0.7812 - val_loss: 0.5019
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7305 - loss: 0.5516 - val_accuracy: 0.8281 - val_loss: 0.4795
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7578 - loss: 0.5309 - val_accuracy: 0.8594 - val_loss: 0.4584
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7812 - loss: 0.5106 - val_accuracy: 0.8594 - val_loss: 0.4383
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8008 - loss: 0.4905 - val_accuracy: 0.8594 - val_loss: 0.4192
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8203 - loss: 0.4713 - val_accuracy: 0.8750 - val_loss: 0.4016
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8281 - loss: 0.4534 - val_accuracy: 0.8750 - val_loss: 0.3858
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.4362 - val_accuracy: 0.8750 - val_loss: 0.3716
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.4204 - val_accuracy: 0.8594 - val_loss: 0.3591
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.4059 - val_accuracy: 0.8438 - val_loss: 0.3483
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.3924 - val_accuracy: 0.8438 - val_loss: 0.3382
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.3798 - val_accuracy: 0.8438 - val_loss: 0.3292
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3681 - val_accuracy: 0.8438 - val_loss: 0.3212
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3569 - val_accuracy: 0.8594 - val_loss: 0.3143
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3468 - val_accuracy: 0.8594 - val_loss: 0.3085
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.3374 - val_accuracy: 0.8594 - val_loss: 0.3034
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3288 - val_accuracy: 0.8438 - val_loss: 0.2991
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3210 - val_accuracy: 0.8438 - val_loss: 0.2956
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.3137 - val_accuracy: 0.8438 - val_loss: 0.2928
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.3068 - val_accuracy: 0.8438 - val_loss: 0.2906
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.3004 - val_accuracy: 0.8594 - val_loss: 0.2890
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2944 - val_accuracy: 0.8594 - val_loss: 0.2878
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.2889 - val_accuracy: 0.8594 - val_loss: 0.2869
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2839 - val_accuracy: 0.8594 - val_loss: 0.2864
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2792 - val_accuracy: 0.8594 - val_loss: 0.2861
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2748 - val_accuracy: 0.8750 - val_loss: 0.2862
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.2707 - val_accuracy: 0.8750 - val_loss: 0.2864
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2670 - val_accuracy: 0.8750 - val_loss: 0.2868
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2634 - val_accuracy: 0.8906 - val_loss: 0.2875
Epoch 37/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2600 - val_accuracy: 0.8906 - val_loss: 0.2884
Epoch 38/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2567 - val_accuracy: 0.8906 - val_loss: 0.2894
Epoch 39/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2537 - val_accuracy: 0.8906 - val_loss: 0.2905
Epoch 40/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2509 - val_accuracy: 0.8906 - val_loss: 0.2917
Epoch 41/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2482 - val_accuracy: 0.8906 - val_loss: 0.2929
Epoch 42/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2457 - val_accuracy: 0.8906 - val_loss: 0.2943
Epoch 43/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2434 - val_accuracy: 0.8750 - val_loss: 0.2957
Epoch 44/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2411 - val_accuracy: 0.8750 - val_loss: 0.2969
Epoch 45/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2390 - val_accuracy: 0.8750 - val_loss: 0.2982
Epoch 46/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2370 - val_accuracy: 0.8750 - val_loss: 0.2995
Epoch 47/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2351 - val_accuracy: 0.8750 - val_loss: 0.3007
Epoch 48/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2333 - val_accuracy: 0.8750 - val_loss: 0.3020
Epoch 49/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2316 - val_accuracy: 0.8750 - val_loss: 0.3033
Epoch 50/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2300 - val_accuracy: 0.8750 - val_loss: 0.3047
Epoch 51/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2284 - val_accuracy: 0.8750 - val_loss: 0.3060
Epoch 52/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2269 - val_accuracy: 0.8750 - val_loss: 0.3071
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8875 - loss: 0.3094
========================
Final Test Loss: 0.30937743186950684
Final Test Accuracy: 0.887499988079071
========================

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 629 (2.46 KB)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 420 (1.64 KB)

In [38]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

tf.keras.utils.set_random_seed(42)


model = Sequential([
    Dense(16, activation='relu', input_shape=(3,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=20,
    restore_best_weights=True
)


history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=8,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)



test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)

print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")


# Network Structure
model.summary()

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.3945 - loss: 0.7644 - val_accuracy: 0.5312 - val_loss: 0.6717
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5391 - loss: 0.6947 - val_accuracy: 0.7656 - val_loss: 0.6099
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6602 - loss: 0.6386 - val_accuracy: 0.7969 - val_loss: 0.5563
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7031 - loss: 0.5893 - val_accuracy: 0.7812 - val_loss: 0.5079
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7383 - loss: 0.5463 - val_accuracy: 0.8281 - val_loss: 0.4651
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7539 - loss: 0.5071 - val_accuracy: 0.8438 - val_loss: 0.4266
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8164 - loss: 0.4701 - val_accuracy: 0.8750 - val_loss: 0.3930
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.4366 - val_accuracy: 0.8750 - val_loss: 0.3647
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.4069 - val_accuracy: 0.8438 - val_loss: 0.3425
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.3810 - val_accuracy: 0.8438 - val_loss: 0.3245
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.3585 - val_accuracy: 0.8594 - val_loss: 0.3104
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.3388 - val_accuracy: 0.8594 - val_loss: 0.3005
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.3221 - val_accuracy: 0.8438 - val_loss: 0.2942
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.3082 - val_accuracy: 0.8438 - val_loss: 0.2901
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.2960 - val_accuracy: 0.8594 - val_loss: 0.2876
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2854 - val_accuracy: 0.8594 - val_loss: 0.2869
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2764 - val_accuracy: 0.8750 - val_loss: 0.2869
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2684 - val_accuracy: 0.8750 - val_loss: 0.2878
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2614 - val_accuracy: 0.8906 - val_loss: 0.2896
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2551 - val_accuracy: 0.8906 - val_loss: 0.2922
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2495 - val_accuracy: 0.8750 - val_loss: 0.2952
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2446 - val_accuracy: 0.8750 - val_loss: 0.2982
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2402 - val_accuracy: 0.8750 - val_loss: 0.3009
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2363 - val_accuracy: 0.8750 - val_loss: 0.3035
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2327 - val_accuracy: 0.8750 - val_loss: 0.3059
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2294 - val_accuracy: 0.8750 - val_loss: 0.3085
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9102 - loss: 0.2263 - val_accuracy: 0.8750 - val_loss: 0.3107
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2235 - val_accuracy: 0.8750 - val_loss: 0.3129
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2210 - val_accuracy: 0.8750 - val_loss: 0.3151
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2187 - val_accuracy: 0.8750 - val_loss: 0.3174
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2166 - val_accuracy: 0.8750 - val_loss: 0.3204
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2147 - val_accuracy: 0.8750 - val_loss: 0.3235
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2129 - val_accuracy: 0.8750 - val_loss: 0.3264
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2113 - val_accuracy: 0.8750 - val_loss: 0.3288
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2098 - val_accuracy: 0.8750 - val_loss: 0.3314
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9258 - loss: 0.2085 - val_accuracy: 0.8750 - val_loss: 0.3341
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8875 - loss: 0.3116
========================
Final Test Loss: 0.3115662932395935
Final Test Accuracy: 0.887499988079071
========================

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 629 (2.46 KB)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 420 (1.64 KB)

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


tf.keras.utils.set_random_seed(42)


model = Sequential([
    Dense(6, activation='relu', input_shape=(3,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])


model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


history = model.fit(
    X_train,
    y_train,
    epochs=150,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("====================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("====================")

Epoch 1/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.3789 - loss: 0.7205 - val_accuracy: 0.3438 - val_loss: 0.7638
Epoch 2/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4414 - loss: 0.6932 - val_accuracy: 0.4844 - val_loss: 0.7315
Epoch 3/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5820 - loss: 0.6682 - val_accuracy: 0.5781 - val_loss: 0.7029
Epoch 4/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6445 - loss: 0.6455 - val_accuracy: 0.6250 - val_loss: 0.6776
Epoch 5/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6758 - loss: 0.6244 - val_accuracy: 0.6562 - val_loss: 0.6547
Epoch 6/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7070 - loss: 0.6040 - val_accuracy: 0.6875 - val_loss: 0.6320
Epoch 7/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7344 - loss: 0.5841 - val_accuracy: 0.7188 - val_loss: 0.6103
Epoch 8/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7734 - loss: 0.5647 - val_accuracy: 0.7500 - val_loss: 0.5902
Epoch 9/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7891 - loss: 0.5453 - val_accuracy: 0.7500 - val_loss: 0.5715
Epoch 10/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8008 - loss: 0.5267 - val_accuracy: 0.7344 - val_loss: 0.5541
Epoch 11/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8125 - loss: 0.5092 - val_accuracy: 0.7500 - val_loss: 0.5379
Epoch 12/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8164 - loss: 0.4930 - val_accuracy: 0.7812 - val_loss: 0.5232
Epoch 13/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8242 - loss: 0.4778 - val_accuracy: 0.7812 - val_loss: 0.5102
Epoch 14/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8281 - loss: 0.4639 - val_accuracy: 0.7969 - val_loss: 0.4989
Epoch 15/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4512 - val_accuracy: 0.7969 - val_loss: 0.4891
Epoch 16/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4395 - val_accuracy: 0.7969 - val_loss: 0.4805
Epoch 17/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4288 - val_accuracy: 0.7969 - val_loss: 0.4729
Epoch 18/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4190 - val_accuracy: 0.7969 - val_loss: 0.4661
Epoch 19/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4101 - val_accuracy: 0.7969 - val_loss: 0.4599
Epoch 20/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4020 - val_accuracy: 0.7969 - val_loss: 0.4545
Epoch 21/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3944 - val_accuracy: 0.7969 - val_loss: 0.4499
Epoch 22/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3873 - val_accuracy: 0.8125 - val_loss: 0.4460
Epoch 23/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8359 - loss: 0.3808 - val_accuracy: 0.8125 - val_loss: 0.4427
Epoch 24/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3746 - val_accuracy: 0.8125 - val_loss: 0.4396
Epoch 25/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3690 - val_accuracy: 0.8125 - val_loss: 0.4371
Epoch 26/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3638 - val_accuracy: 0.8125 - val_loss: 0.4351
Epoch 27/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3589 - val_accuracy: 0.8125 - val_loss: 0.4333
Epoch 28/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3546 - val_accuracy: 0.8125 - val_loss: 0.4319
Epoch 29/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3507 - val_accuracy: 0.8125 - val_loss: 0.4310
Epoch 30/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8359 - loss: 0.3472 - val_accuracy: 0.8125 - val_loss: 0.4303
Epoch 31/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3439 - val_accuracy: 0.8125 - val_loss: 0.4297
Epoch 32/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3409 - val_accuracy: 0.8125 - val_loss: 0.4293
Epoch 33/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3381 - val_accuracy: 0.8125 - val_loss: 0.4291
Epoch 34/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3356 - val_accuracy: 0.8125 - val_loss: 0.4289
Epoch 35/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3333 - val_accuracy: 0.8125 - val_loss: 0.4289
Epoch 36/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3313 - val_accuracy: 0.8125 - val_loss: 0.4290
Epoch 37/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3294 - val_accuracy: 0.8125 - val_loss: 0.4292
Epoch 38/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3275 - val_accuracy: 0.8125 - val_loss: 0.4294
Epoch 39/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3258 - val_accuracy: 0.8125 - val_loss: 0.4297
Epoch 40/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3243 - val_accuracy: 0.8125 - val_loss: 0.4301
Epoch 41/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3229 - val_accuracy: 0.8125 - val_loss: 0.4304
Epoch 42/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8477 - loss: 0.3216 - val_accuracy: 0.8125 - val_loss: 0.4307
Epoch 43/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3203 - val_accuracy: 0.8125 - val_loss: 0.4310
Epoch 44/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8555 - loss: 0.3191 - val_accuracy: 0.8125 - val_loss: 0.4312
Epoch 45/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3179 - val_accuracy: 0.8125 - val_loss: 0.4315
Epoch 46/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8477 - loss: 0.3168 - val_accuracy: 0.8125 - val_loss: 0.4317
Epoch 47/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3157 - val_accuracy: 0.8125 - val_loss: 0.4318
Epoch 48/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3147 - val_accuracy: 0.8125 - val_loss: 0.4319
Epoch 49/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3137 - val_accuracy: 0.8125 - val_loss: 0.4320
Epoch 50/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3128 - val_accuracy: 0.8125 - val_loss: 0.4320
Epoch 51/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3120 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 52/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3112 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 53/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3104 - val_accuracy: 0.8125 - val_loss: 0.4322
Epoch 54/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3096 - val_accuracy: 0.8125 - val_loss: 0.4324
Epoch 55/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3088 - val_accuracy: 0.8125 - val_loss: 0.4326
Epoch 56/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3080 - val_accuracy: 0.8125 - val_loss: 0.4328
Epoch 57/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3073 - val_accuracy: 0.8125 - val_loss: 0.4330
Epoch 58/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3066 - val_accuracy: 0.8125 - val_loss: 0.4332
Epoch 59/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3060 - val_accuracy: 0.8125 - val_loss: 0.4334
Epoch 60/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3053 - val_accuracy: 0.8125 - val_loss: 0.4336
Epoch 61/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3046 - val_accuracy: 0.8125 - val_loss: 0.4338
Epoch 62/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8555 - loss: 0.3038 - val_accuracy: 0.8125 - val_loss: 0.4339
Epoch 63/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3031 - val_accuracy: 0.8125 - val_loss: 0.4341
Epoch 64/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3025 - val_accuracy: 0.8125 - val_loss: 0.4342
Epoch 65/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3019 - val_accuracy: 0.8125 - val_loss: 0.4343
Epoch 66/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3012 - val_accuracy: 0.8125 - val_loss: 0.4343
Epoch 67/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3005 - val_accuracy: 0.7969 - val_loss: 0.4343
Epoch 68/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2998 - val_accuracy: 0.7969 - val_loss: 0.4342
Epoch 69/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8555 - loss: 0.2991 - val_accuracy: 0.7969 - val_loss: 0.4341
Epoch 70/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2984 - val_accuracy: 0.7969 - val_loss: 0.4340
Epoch 71/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2976 - val_accuracy: 0.7969 - val_loss: 0.4339
Epoch 72/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2968 - val_accuracy: 0.7969 - val_loss: 0.4337
Epoch 73/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2959 - val_accuracy: 0.8125 - val_loss: 0.4334
Epoch 74/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2951 - val_accuracy: 0.8125 - val_loss: 0.4330
Epoch 75/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2943 - val_accuracy: 0.8125 - val_loss: 0.4328
Epoch 76/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2934 - val_accuracy: 0.8125 - val_loss: 0.4325
Epoch 77/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2925 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 78/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2916 - val_accuracy: 0.8125 - val_loss: 0.4318
Epoch 79/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2907 - val_accuracy: 0.8125 - val_loss: 0.4315
Epoch 80/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2898 - val_accuracy: 0.8281 - val_loss: 0.4312
Epoch 81/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2889 - val_accuracy: 0.8281 - val_loss: 0.4310
Epoch 82/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2880 - val_accuracy: 0.8281 - val_loss: 0.4308
Epoch 83/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2870 - val_accuracy: 0.8281 - val_loss: 0.4305
Epoch 84/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2860 - val_accuracy: 0.8281 - val_loss: 0.4303
Epoch 85/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2849 - val_accuracy: 0.8281 - val_loss: 0.4300
Epoch 86/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2839 - val_accuracy: 0.8281 - val_loss: 0.4299
Epoch 87/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8555 - loss: 0.2830 - val_accuracy: 0.8281 - val_loss: 0.4298
Epoch 88/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2820 - val_accuracy: 0.8281 - val_loss: 0.4297
Epoch 89/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2811 - val_accuracy: 0.8281 - val_loss: 0.4295
Epoch 90/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2803 - val_accuracy: 0.8281 - val_loss: 0.4294
Epoch 91/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.2794 - val_accuracy: 0.8281 - val_loss: 0.4292
Epoch 92/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2786 - val_accuracy: 0.8438 - val_loss: 0.4292
Epoch 93/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2779 - val_accuracy: 0.8438 - val_loss: 0.4290
Epoch 94/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.2771 - val_accuracy: 0.8438 - val_loss: 0.4289
Epoch 95/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2763 - val_accuracy: 0.8438 - val_loss: 0.4288
Epoch 96/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2756 - val_accuracy: 0.8438 - val_loss: 0.4287
Epoch 97/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2749 - val_accuracy: 0.8438 - val_loss: 0.4287
Epoch 98/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2742 - val_accuracy: 0.8438 - val_loss: 0.4286
Epoch 99/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2734 - val_accuracy: 0.8438 - val_loss: 0.4286
Epoch 100/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2727 - val_accuracy: 0.8438 - val_loss: 0.4285
Epoch 101/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2720 - val_accuracy: 0.8438 - val_loss: 0.4285
Epoch 102/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2713 - val_accuracy: 0.8438 - val_loss: 0.4285
Epoch 103/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2707 - val_accuracy: 0.8438 - val_loss: 0.4285
Epoch 104/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2700 - val_accuracy: 0.8438 - val_loss: 0.4284
Epoch 105/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2693 - val_accuracy: 0.8438 - val_loss: 0.4285
Epoch 106/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8711 - loss: 0.2686 - val_accuracy: 0.8438 - val_loss: 0.4284
Epoch 107/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8711 - loss: 0.2679 - val_accuracy: 0.8438 - val_loss: 0.4284
Epoch 108/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.2672 - val_accuracy: 0.8438 - val_loss: 0.4283
Epoch 109/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2665 - val_accuracy: 0.8438 - val_loss: 0.4283
Epoch 110/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2658 - val_accuracy: 0.8438 - val_loss: 0.4283
Epoch 111/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2652 - val_accuracy: 0.8438 - val_loss: 0.4281
Epoch 112/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2645 - val_accuracy: 0.8438 - val_loss: 0.4279
Epoch 113/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2638 - val_accuracy: 0.8281 - val_loss: 0.4278
Epoch 114/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.2632 - val_accuracy: 0.8281 - val_loss: 0.4277
Epoch 115/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8789 - loss: 0.2626 - val_accuracy: 0.8281 - val_loss: 0.4276
Epoch 116/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8789 - loss: 0.2620 - val_accuracy: 0.8281 - val_loss: 0.4276
Epoch 117/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2614 - val_accuracy: 0.8281 - val_loss: 0.4274
Epoch 118/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8789 - loss: 0.2608 - val_accuracy: 0.8281 - val_loss: 0.4274
Epoch 119/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2602 - val_accuracy: 0.8281 - val_loss: 0.4273
Epoch 120/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2596 - val_accuracy: 0.8438 - val_loss: 0.4272
Epoch 121/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2591 - val_accuracy: 0.8438 - val_loss: 0.4272
Epoch 122/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2586 - val_accuracy: 0.8438 - val_loss: 0.4272
Epoch 123/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2580 - val_accuracy: 0.8438 - val_loss: 0.4271
Epoch 124/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2575 - val_accuracy: 0.8438 - val_loss: 0.4271
Epoch 125/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2570 - val_accuracy: 0.8438 - val_loss: 0.4271
Epoch 126/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2565 - val_accuracy: 0.8438 - val_loss: 0.4270
Epoch 127/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2559 - val_accuracy: 0.8438 - val_loss: 0.4270
Epoch 128/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2554 - val_accuracy: 0.8438 - val_loss: 0.4269
Epoch 129/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2549 - val_accuracy: 0.8438 - val_loss: 0.4268
Epoch 130/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2544 - val_accuracy: 0.8438 - val_loss: 0.4268
Epoch 131/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2539 - val_accuracy: 0.8438 - val_loss: 0.4268
Epoch 132/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2534 - val_accuracy: 0.8438 - val_loss: 0.4266
Epoch 133/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8867 - loss: 0.2529 - val_accuracy: 0.8438 - val_loss: 0.4266
Epoch 134/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2524 - val_accuracy: 0.8438 - val_loss: 0.4265
Epoch 135/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2519 - val_accuracy: 0.8438 - val_loss: 0.4265
Epoch 136/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2514 - val_accuracy: 0.8438 - val_loss: 0.4265
Epoch 137/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2509 - val_accuracy: 0.8438 - val_loss: 0.4264
Epoch 138/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2505 - val_accuracy: 0.8438 - val_loss: 0.4264
Epoch 139/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2500 - val_accuracy: 0.8438 - val_loss: 0.4264
Epoch 140/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2495 - val_accuracy: 0.8438 - val_loss: 0.4263
Epoch 141/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2490 - val_accuracy: 0.8438 - val_loss: 0.4263
Epoch 142/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2485 - val_accuracy: 0.8438 - val_loss: 0.4263
Epoch 143/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2480 - val_accuracy: 0.8438 - val_loss: 0.4262
Epoch 144/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2475 - val_accuracy: 0.8438 - val_loss: 0.4262
Epoch 145/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2470 - val_accuracy: 0.8438 - val_loss: 0.4261
Epoch 146/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2465 - val_accuracy: 0.8438 - val_loss: 0.4260
Epoch 147/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2460 - val_accuracy: 0.8438 - val_loss: 0.4260
Epoch 148/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2455 - val_accuracy: 0.8438 - val_loss: 0.4260
Epoch 149/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2451 - val_accuracy: 0.8438 - val_loss: 0.4258
Epoch 150/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2446 - val_accuracy: 0.8438 - val_loss: 0.4258
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8500 - loss: 0.3343
====================
Final Test Loss: 0.3343425989151001
Final Test Accuracy: 0.8500000238418579
====================

In [40]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


tf.keras.utils.set_random_seed(42)


model = Sequential([
    Dense(6, activation='tanh', input_shape=(3,)),
    Dense(4, activation='tanh'),
    Dense(1, activation='sigmoid')
])


model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


history = model.fit(
    X_train,
    y_train,
    epochs=150,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")


model.summary()

Epoch 1/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.5664 - loss: 0.6777 - val_accuracy: 0.6094 - val_loss: 0.6539
Epoch 2/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.6367 - loss: 0.6317 - val_accuracy: 0.6719 - val_loss: 0.6127
Epoch 3/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7148 - loss: 0.5917 - val_accuracy: 0.7031 - val_loss: 0.5775
Epoch 4/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7539 - loss: 0.5567 - val_accuracy: 0.7812 - val_loss: 0.5470
Epoch 5/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7812 - loss: 0.5260 - val_accuracy: 0.7656 - val_loss: 0.5207
Epoch 6/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.8164 - loss: 0.4988 - val_accuracy: 0.7812 - val_loss: 0.4980
Epoch 7/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8164 - loss: 0.4745 - val_accuracy: 0.7969 - val_loss: 0.4784
Epoch 8/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8242 - loss: 0.4528 - val_accuracy: 0.8125 - val_loss: 0.4615
Epoch 9/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8320 - loss: 0.4334 - val_accuracy: 0.8125 - val_loss: 0.4470
Epoch 10/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.4161 - val_accuracy: 0.8125 - val_loss: 0.4346
Epoch 11/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.4008 - val_accuracy: 0.8281 - val_loss: 0.4240
Epoch 12/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3873 - val_accuracy: 0.8125 - val_loss: 0.4150
Epoch 13/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3755 - val_accuracy: 0.8281 - val_loss: 0.4074
Epoch 14/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3654 - val_accuracy: 0.8281 - val_loss: 0.4012
Epoch 15/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3569 - val_accuracy: 0.8281 - val_loss: 0.3962
Epoch 16/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3497 - val_accuracy: 0.8281 - val_loss: 0.3923
Epoch 17/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3437 - val_accuracy: 0.8281 - val_loss: 0.3893
Epoch 18/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3387 - val_accuracy: 0.8125 - val_loss: 0.3871
Epoch 19/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3346 - val_accuracy: 0.8281 - val_loss: 0.3855
Epoch 20/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3312 - val_accuracy: 0.8281 - val_loss: 0.3844
Epoch 21/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3284 - val_accuracy: 0.8281 - val_loss: 0.3837
Epoch 22/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3261 - val_accuracy: 0.8281 - val_loss: 0.3833
Epoch 23/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3241 - val_accuracy: 0.8281 - val_loss: 0.3832
Epoch 24/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3224 - val_accuracy: 0.8281 - val_loss: 0.3832
Epoch 25/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3210 - val_accuracy: 0.8281 - val_loss: 0.3834
Epoch 26/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3198 - val_accuracy: 0.8281 - val_loss: 0.3837
Epoch 27/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3187 - val_accuracy: 0.8281 - val_loss: 0.3841
Epoch 28/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8438 - loss: 0.3178 - val_accuracy: 0.8281 - val_loss: 0.3845
Epoch 29/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3169 - val_accuracy: 0.8281 - val_loss: 0.3849
Epoch 30/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3162 - val_accuracy: 0.8281 - val_loss: 0.3854
Epoch 31/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3155 - val_accuracy: 0.8281 - val_loss: 0.3860
Epoch 32/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3149 - val_accuracy: 0.8281 - val_loss: 0.3865
Epoch 33/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3143 - val_accuracy: 0.8281 - val_loss: 0.3870
Epoch 34/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3137 - val_accuracy: 0.8281 - val_loss: 0.3875
Epoch 35/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3132 - val_accuracy: 0.8281 - val_loss: 0.3881
Epoch 36/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3127 - val_accuracy: 0.8281 - val_loss: 0.3886
Epoch 37/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3122 - val_accuracy: 0.8281 - val_loss: 0.3891
Epoch 38/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3117 - val_accuracy: 0.8281 - val_loss: 0.3896
Epoch 39/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3112 - val_accuracy: 0.8281 - val_loss: 0.3901
Epoch 40/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3108 - val_accuracy: 0.8281 - val_loss: 0.3905
Epoch 41/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3103 - val_accuracy: 0.8281 - val_loss: 0.3910
Epoch 42/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3098 - val_accuracy: 0.8281 - val_loss: 0.3914
Epoch 43/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3094 - val_accuracy: 0.8281 - val_loss: 0.3919
Epoch 44/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3089 - val_accuracy: 0.8281 - val_loss: 0.3923
Epoch 45/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3084 - val_accuracy: 0.8281 - val_loss: 0.3927
Epoch 46/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3079 - val_accuracy: 0.8281 - val_loss: 0.3931
Epoch 47/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3075 - val_accuracy: 0.8281 - val_loss: 0.3934
Epoch 48/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3070 - val_accuracy: 0.8281 - val_loss: 0.3938
Epoch 49/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3065 - val_accuracy: 0.8281 - val_loss: 0.3941
Epoch 50/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3059 - val_accuracy: 0.8281 - val_loss: 0.3945
Epoch 51/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3054 - val_accuracy: 0.8281 - val_loss: 0.3948
Epoch 52/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3049 - val_accuracy: 0.8281 - val_loss: 0.3951
Epoch 53/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3043 - val_accuracy: 0.8281 - val_loss: 0.3954
Epoch 54/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3038 - val_accuracy: 0.8281 - val_loss: 0.3956
Epoch 55/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3032 - val_accuracy: 0.8281 - val_loss: 0.3959
Epoch 56/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3026 - val_accuracy: 0.8281 - val_loss: 0.3962
Epoch 57/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3021 - val_accuracy: 0.8281 - val_loss: 0.3964
Epoch 58/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3015 - val_accuracy: 0.8281 - val_loss: 0.3967
Epoch 59/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3009 - val_accuracy: 0.8281 - val_loss: 0.3969
Epoch 60/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3003 - val_accuracy: 0.8281 - val_loss: 0.3971
Epoch 61/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.2996 - val_accuracy: 0.8281 - val_loss: 0.3974
Epoch 62/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.2990 - val_accuracy: 0.8281 - val_loss: 0.3976
Epoch 63/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.2984 - val_accuracy: 0.8281 - val_loss: 0.3978
Epoch 64/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.2977 - val_accuracy: 0.8281 - val_loss: 0.3980
Epoch 65/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.2971 - val_accuracy: 0.8281 - val_loss: 0.3983
Epoch 66/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.2964 - val_accuracy: 0.8281 - val_loss: 0.3985
Epoch 67/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2958 - val_accuracy: 0.8281 - val_loss: 0.3987
Epoch 68/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2951 - val_accuracy: 0.8438 - val_loss: 0.3989
Epoch 69/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2944 - val_accuracy: 0.8438 - val_loss: 0.3992
Epoch 70/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2937 - val_accuracy: 0.8438 - val_loss: 0.3994
Epoch 71/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.2930 - val_accuracy: 0.8438 - val_loss: 0.3997
Epoch 72/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.2923 - val_accuracy: 0.8438 - val_loss: 0.3999
Epoch 73/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2916 - val_accuracy: 0.8438 - val_loss: 0.4002
Epoch 74/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.2909 - val_accuracy: 0.8438 - val_loss: 0.4005
Epoch 75/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2902 - val_accuracy: 0.8438 - val_loss: 0.4007
Epoch 76/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.2894 - val_accuracy: 0.8438 - val_loss: 0.4010
Epoch 77/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2887 - val_accuracy: 0.8438 - val_loss: 0.4013
Epoch 78/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.2879 - val_accuracy: 0.8438 - val_loss: 0.4017
Epoch 79/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2871 - val_accuracy: 0.8438 - val_loss: 0.4020
Epoch 80/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2864 - val_accuracy: 0.8438 - val_loss: 0.4023
Epoch 81/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2856 - val_accuracy: 0.8438 - val_loss: 0.4027
Epoch 82/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2847 - val_accuracy: 0.8438 - val_loss: 0.4031
Epoch 83/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2839 - val_accuracy: 0.8438 - val_loss: 0.4034
Epoch 84/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2831 - val_accuracy: 0.8438 - val_loss: 0.4038
Epoch 85/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2822 - val_accuracy: 0.8438 - val_loss: 0.4043
Epoch 86/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2813 - val_accuracy: 0.8438 - val_loss: 0.4047
Epoch 87/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2803 - val_accuracy: 0.8438 - val_loss: 0.4051
Epoch 88/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2794 - val_accuracy: 0.8438 - val_loss: 0.4056
Epoch 89/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2784 - val_accuracy: 0.8438 - val_loss: 0.4061
Epoch 90/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.2774 - val_accuracy: 0.8438 - val_loss: 0.4066
Epoch 91/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2763 - val_accuracy: 0.8438 - val_loss: 0.4070
Epoch 92/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2752 - val_accuracy: 0.8438 - val_loss: 0.4075
Epoch 93/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2741 - val_accuracy: 0.8438 - val_loss: 0.4080
Epoch 94/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2729 - val_accuracy: 0.8438 - val_loss: 0.4085
Epoch 95/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2717 - val_accuracy: 0.8438 - val_loss: 0.4090
Epoch 96/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2705 - val_accuracy: 0.8438 - val_loss: 0.4094
Epoch 97/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2692 - val_accuracy: 0.8438 - val_loss: 0.4098
Epoch 98/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.2679 - val_accuracy: 0.8438 - val_loss: 0.4102
Epoch 99/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8672 - loss: 0.2665 - val_accuracy: 0.8281 - val_loss: 0.4105
Epoch 100/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8711 - loss: 0.2651 - val_accuracy: 0.8281 - val_loss: 0.4108
Epoch 101/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8711 - loss: 0.2637 - val_accuracy: 0.8281 - val_loss: 0.4110
Epoch 102/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.2623 - val_accuracy: 0.8281 - val_loss: 0.4112
Epoch 103/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.2608 - val_accuracy: 0.8281 - val_loss: 0.4112
Epoch 104/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.2594 - val_accuracy: 0.8281 - val_loss: 0.4112
Epoch 105/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2579 - val_accuracy: 0.8281 - val_loss: 0.4111
Epoch 106/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8789 - loss: 0.2564 - val_accuracy: 0.8281 - val_loss: 0.4110
Epoch 107/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2548 - val_accuracy: 0.8281 - val_loss: 0.4107
Epoch 108/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2533 - val_accuracy: 0.8281 - val_loss: 0.4103
Epoch 109/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8828 - loss: 0.2517 - val_accuracy: 0.8438 - val_loss: 0.4099
Epoch 110/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2502 - val_accuracy: 0.8438 - val_loss: 0.4093
Epoch 111/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2486 - val_accuracy: 0.8438 - val_loss: 0.4087
Epoch 112/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2471 - val_accuracy: 0.8438 - val_loss: 0.4080
Epoch 113/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2455 - val_accuracy: 0.8438 - val_loss: 0.4072
Epoch 114/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2439 - val_accuracy: 0.8438 - val_loss: 0.4063
Epoch 115/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2424 - val_accuracy: 0.8594 - val_loss: 0.4053
Epoch 116/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.2408 - val_accuracy: 0.8594 - val_loss: 0.4044
Epoch 117/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8906 - loss: 0.2392 - val_accuracy: 0.8594 - val_loss: 0.4033
Epoch 118/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.2377 - val_accuracy: 0.8594 - val_loss: 0.4022
Epoch 119/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.2361 - val_accuracy: 0.8750 - val_loss: 0.4011
Epoch 120/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8984 - loss: 0.2346 - val_accuracy: 0.8750 - val_loss: 0.3999
Epoch 121/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2331 - val_accuracy: 0.8750 - val_loss: 0.3988
Epoch 122/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2316 - val_accuracy: 0.8750 - val_loss: 0.3976
Epoch 123/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2301 - val_accuracy: 0.8750 - val_loss: 0.3964
Epoch 124/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2286 - val_accuracy: 0.8750 - val_loss: 0.3953
Epoch 125/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2271 - val_accuracy: 0.8750 - val_loss: 0.3942
Epoch 126/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9102 - loss: 0.2257 - val_accuracy: 0.8750 - val_loss: 0.3931
Epoch 127/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2242 - val_accuracy: 0.8750 - val_loss: 0.3920
Epoch 128/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2228 - val_accuracy: 0.8750 - val_loss: 0.3910
Epoch 129/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2214 - val_accuracy: 0.8750 - val_loss: 0.3900
Epoch 130/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2201 - val_accuracy: 0.8750 - val_loss: 0.3890
Epoch 131/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2187 - val_accuracy: 0.8750 - val_loss: 0.3882
Epoch 132/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9258 - loss: 0.2174 - val_accuracy: 0.8750 - val_loss: 0.3874
Epoch 133/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9258 - loss: 0.2161 - val_accuracy: 0.8750 - val_loss: 0.3866
Epoch 134/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9297 - loss: 0.2148 - val_accuracy: 0.8594 - val_loss: 0.3859
Epoch 135/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2136 - val_accuracy: 0.8750 - val_loss: 0.3853
Epoch 136/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2124 - val_accuracy: 0.8750 - val_loss: 0.3847
Epoch 137/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2112 - val_accuracy: 0.8750 - val_loss: 0.3842
Epoch 138/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2101 - val_accuracy: 0.8750 - val_loss: 0.3837
Epoch 139/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2089 - val_accuracy: 0.8750 - val_loss: 0.3833
Epoch 140/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9375 - loss: 0.2078 - val_accuracy: 0.8750 - val_loss: 0.3830
Epoch 141/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.2068 - val_accuracy: 0.8750 - val_loss: 0.3827
Epoch 142/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.2057 - val_accuracy: 0.8750 - val_loss: 0.3824
Epoch 143/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.2047 - val_accuracy: 0.8750 - val_loss: 0.3823
Epoch 144/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.2037 - val_accuracy: 0.8750 - val_loss: 0.3821
Epoch 145/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.2028 - val_accuracy: 0.8750 - val_loss: 0.3820
Epoch 146/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.2018 - val_accuracy: 0.8750 - val_loss: 0.3820
Epoch 147/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.2009 - val_accuracy: 0.8750 - val_loss: 0.3820
Epoch 148/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.2000 - val_accuracy: 0.8750 - val_loss: 0.3820
Epoch 149/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.1992 - val_accuracy: 0.8750 - val_loss: 0.3821
Epoch 150/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9375 - loss: 0.1984 - val_accuracy: 0.8750 - val_loss: 0.3822
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9000 - loss: 0.2585
========================
Final Test Loss: 0.258486270904541
Final Test Accuracy: 0.8999999761581421
========================

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 6)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (696.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 116 (468.00 B)

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU
from tensorflow.keras.optimizers import Adam


tf.keras.utils.set_random_seed(42)


model = Sequential([
    Dense(8, input_shape=(3,)),
    LeakyReLU(alpha=0.1),

    Dense(4),
    LeakyReLU(alpha=0.1),

    Dense(1, activation='sigmoid')
])


model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


history = model.fit(
    X_train,
    y_train,
    epochs=150,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)

Epoch 1/150

/usr/local/lib/python3.12/dist-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.5156 - loss: 0.7153 - val_accuracy: 0.4375 - val_loss: 0.7257
Epoch 2/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5977 - loss: 0.6766 - val_accuracy: 0.5312 - val_loss: 0.6878
Epoch 3/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6406 - loss: 0.6462 - val_accuracy: 0.6094 - val_loss: 0.6603
Epoch 4/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7070 - loss: 0.6195 - val_accuracy: 0.6875 - val_loss: 0.6393
Epoch 5/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7617 - loss: 0.5936 - val_accuracy: 0.7188 - val_loss: 0.6209
Epoch 6/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8008 - loss: 0.5674 - val_accuracy: 0.7344 - val_loss: 0.6016
Epoch 7/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8477 - loss: 0.5374 - val_accuracy: 0.7656 - val_loss: 0.5785
Epoch 8/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.5033 - val_accuracy: 0.7969 - val_loss: 0.5520
Epoch 9/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8906 - loss: 0.4657 - val_accuracy: 0.8125 - val_loss: 0.5234
Epoch 10/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8984 - loss: 0.4262 - val_accuracy: 0.8281 - val_loss: 0.4941
Epoch 11/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.3898 - val_accuracy: 0.8125 - val_loss: 0.4702
Epoch 12/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.3587 - val_accuracy: 0.8125 - val_loss: 0.4526
Epoch 13/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9219 - loss: 0.3335 - val_accuracy: 0.8125 - val_loss: 0.4404
Epoch 14/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.3132 - val_accuracy: 0.8125 - val_loss: 0.4322
Epoch 15/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9141 - loss: 0.2969 - val_accuracy: 0.8125 - val_loss: 0.4264
Epoch 16/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2838 - val_accuracy: 0.8125 - val_loss: 0.4227
Epoch 17/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2730 - val_accuracy: 0.8125 - val_loss: 0.4203
Epoch 18/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2642 - val_accuracy: 0.8125 - val_loss: 0.4187
Epoch 19/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2568 - val_accuracy: 0.8281 - val_loss: 0.4176
Epoch 20/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2505 - val_accuracy: 0.8438 - val_loss: 0.4168
Epoch 21/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2452 - val_accuracy: 0.8438 - val_loss: 0.4162
Epoch 22/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2405 - val_accuracy: 0.8438 - val_loss: 0.4159
Epoch 23/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2363 - val_accuracy: 0.8438 - val_loss: 0.4159
Epoch 24/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9297 - loss: 0.2326 - val_accuracy: 0.8438 - val_loss: 0.4160
Epoch 25/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2293 - val_accuracy: 0.8438 - val_loss: 0.4162
Epoch 26/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2264 - val_accuracy: 0.8438 - val_loss: 0.4164
Epoch 27/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2238 - val_accuracy: 0.8438 - val_loss: 0.4169
Epoch 28/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2214 - val_accuracy: 0.8438 - val_loss: 0.4173
Epoch 29/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2194 - val_accuracy: 0.8438 - val_loss: 0.4178
Epoch 30/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2175 - val_accuracy: 0.8438 - val_loss: 0.4181
Epoch 31/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2158 - val_accuracy: 0.8438 - val_loss: 0.4186
Epoch 32/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9336 - loss: 0.2142 - val_accuracy: 0.8594 - val_loss: 0.4190
Epoch 33/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2127 - val_accuracy: 0.8594 - val_loss: 0.4195
Epoch 34/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2114 - val_accuracy: 0.8594 - val_loss: 0.4199
Epoch 35/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2102 - val_accuracy: 0.8594 - val_loss: 0.4205
Epoch 36/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2090 - val_accuracy: 0.8594 - val_loss: 0.4211
Epoch 37/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2079 - val_accuracy: 0.8594 - val_loss: 0.4216
Epoch 38/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9336 - loss: 0.2069 - val_accuracy: 0.8594 - val_loss: 0.4222
Epoch 39/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2059 - val_accuracy: 0.8594 - val_loss: 0.4228
Epoch 40/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2049 - val_accuracy: 0.8594 - val_loss: 0.4235
Epoch 41/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2041 - val_accuracy: 0.8594 - val_loss: 0.4242
Epoch 42/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2032 - val_accuracy: 0.8594 - val_loss: 0.4247
Epoch 43/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9375 - loss: 0.2024 - val_accuracy: 0.8594 - val_loss: 0.4255
Epoch 44/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2015 - val_accuracy: 0.8594 - val_loss: 0.4263
Epoch 45/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2007 - val_accuracy: 0.8594 - val_loss: 0.4269
Epoch 46/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.2000 - val_accuracy: 0.8594 - val_loss: 0.4274
Epoch 47/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1993 - val_accuracy: 0.8594 - val_loss: 0.4281
Epoch 48/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1986 - val_accuracy: 0.8594 - val_loss: 0.4287
Epoch 49/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1979 - val_accuracy: 0.8750 - val_loss: 0.4295
Epoch 50/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.1972 - val_accuracy: 0.8750 - val_loss: 0.4301
Epoch 51/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1966 - val_accuracy: 0.8750 - val_loss: 0.4309
Epoch 52/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1960 - val_accuracy: 0.8750 - val_loss: 0.4315
Epoch 53/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1955 - val_accuracy: 0.8750 - val_loss: 0.4320
Epoch 54/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1949 - val_accuracy: 0.8750 - val_loss: 0.4326
Epoch 55/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1944 - val_accuracy: 0.8750 - val_loss: 0.4332
Epoch 56/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1939 - val_accuracy: 0.8750 - val_loss: 0.4338
Epoch 57/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1934 - val_accuracy: 0.8750 - val_loss: 0.4345
Epoch 58/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1929 - val_accuracy: 0.8750 - val_loss: 0.4352
Epoch 59/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1924 - val_accuracy: 0.8750 - val_loss: 0.4359
Epoch 60/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.1920 - val_accuracy: 0.8750 - val_loss: 0.4366
Epoch 61/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1915 - val_accuracy: 0.8750 - val_loss: 0.4372
Epoch 62/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1911 - val_accuracy: 0.8750 - val_loss: 0.4379
Epoch 63/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1907 - val_accuracy: 0.8594 - val_loss: 0.4387
Epoch 64/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1903 - val_accuracy: 0.8594 - val_loss: 0.4393
Epoch 65/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1899 - val_accuracy: 0.8594 - val_loss: 0.4399
Epoch 66/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1896 - val_accuracy: 0.8594 - val_loss: 0.4405
Epoch 67/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1892 - val_accuracy: 0.8594 - val_loss: 0.4412
Epoch 68/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1889 - val_accuracy: 0.8750 - val_loss: 0.4417
Epoch 69/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.1884 - val_accuracy: 0.8750 - val_loss: 0.4420
Epoch 70/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1880 - val_accuracy: 0.8750 - val_loss: 0.4422
Epoch 71/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1875 - val_accuracy: 0.8750 - val_loss: 0.4423
Epoch 72/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1871 - val_accuracy: 0.8750 - val_loss: 0.4425
Epoch 73/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9414 - loss: 0.1867 - val_accuracy: 0.8750 - val_loss: 0.4425
Epoch 74/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1862 - val_accuracy: 0.8750 - val_loss: 0.4425
Epoch 75/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1858 - val_accuracy: 0.8750 - val_loss: 0.4426
Epoch 76/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9414 - loss: 0.1854 - val_accuracy: 0.8750 - val_loss: 0.4427
Epoch 77/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1849 - val_accuracy: 0.8750 - val_loss: 0.4427
Epoch 78/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1845 - val_accuracy: 0.8750 - val_loss: 0.4427
Epoch 79/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9414 - loss: 0.1841 - val_accuracy: 0.8750 - val_loss: 0.4427
Epoch 80/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1838 - val_accuracy: 0.8750 - val_loss: 0.4426
Epoch 81/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9414 - loss: 0.1834 - val_accuracy: 0.8750 - val_loss: 0.4424
Epoch 82/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1831 - val_accuracy: 0.8750 - val_loss: 0.4424
Epoch 83/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1828 - val_accuracy: 0.8750 - val_loss: 0.4426
Epoch 84/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1825 - val_accuracy: 0.8750 - val_loss: 0.4425
Epoch 85/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1822 - val_accuracy: 0.8594 - val_loss: 0.4427
Epoch 86/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1819 - val_accuracy: 0.8750 - val_loss: 0.4429
Epoch 87/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1816 - val_accuracy: 0.8594 - val_loss: 0.4430
Epoch 88/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1814 - val_accuracy: 0.8594 - val_loss: 0.4433
Epoch 89/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1811 - val_accuracy: 0.8594 - val_loss: 0.4435
Epoch 90/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1809 - val_accuracy: 0.8594 - val_loss: 0.4437
Epoch 91/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1807 - val_accuracy: 0.8594 - val_loss: 0.4440
Epoch 92/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1805 - val_accuracy: 0.8594 - val_loss: 0.4443
Epoch 93/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1803 - val_accuracy: 0.8594 - val_loss: 0.4447
Epoch 94/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1800 - val_accuracy: 0.8594 - val_loss: 0.4449
Epoch 95/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1798 - val_accuracy: 0.8594 - val_loss: 0.4453
Epoch 96/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1796 - val_accuracy: 0.8594 - val_loss: 0.4456
Epoch 97/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1794 - val_accuracy: 0.8594 - val_loss: 0.4460
Epoch 98/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1792 - val_accuracy: 0.8594 - val_loss: 0.4464
Epoch 99/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1790 - val_accuracy: 0.8594 - val_loss: 0.4468
Epoch 100/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1788 - val_accuracy: 0.8594 - val_loss: 0.4472
Epoch 101/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1787 - val_accuracy: 0.8594 - val_loss: 0.4477
Epoch 102/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1785 - val_accuracy: 0.8594 - val_loss: 0.4481
Epoch 103/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1783 - val_accuracy: 0.8594 - val_loss: 0.4486
Epoch 104/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1781 - val_accuracy: 0.8594 - val_loss: 0.4490
Epoch 105/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1779 - val_accuracy: 0.8594 - val_loss: 0.4493
Epoch 106/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1777 - val_accuracy: 0.8594 - val_loss: 0.4498
Epoch 107/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1775 - val_accuracy: 0.8594 - val_loss: 0.4502
Epoch 108/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1774 - val_accuracy: 0.8594 - val_loss: 0.4508
Epoch 109/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1772 - val_accuracy: 0.8594 - val_loss: 0.4510
Epoch 110/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1770 - val_accuracy: 0.8594 - val_loss: 0.4513
Epoch 111/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1769 - val_accuracy: 0.8594 - val_loss: 0.4518
Epoch 112/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1767 - val_accuracy: 0.8594 - val_loss: 0.4521
Epoch 113/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1765 - val_accuracy: 0.8594 - val_loss: 0.4524
Epoch 114/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1764 - val_accuracy: 0.8594 - val_loss: 0.4528
Epoch 115/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1762 - val_accuracy: 0.8594 - val_loss: 0.4531
Epoch 116/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1761 - val_accuracy: 0.8438 - val_loss: 0.4537
Epoch 117/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1759 - val_accuracy: 0.8438 - val_loss: 0.4539
Epoch 118/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1758 - val_accuracy: 0.8594 - val_loss: 0.4543
Epoch 119/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1756 - val_accuracy: 0.8438 - val_loss: 0.4547
Epoch 120/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1754 - val_accuracy: 0.8438 - val_loss: 0.4549
Epoch 121/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1752 - val_accuracy: 0.8438 - val_loss: 0.4552
Epoch 122/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1750 - val_accuracy: 0.8438 - val_loss: 0.4556
Epoch 123/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1748 - val_accuracy: 0.8438 - val_loss: 0.4559
Epoch 124/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1746 - val_accuracy: 0.8438 - val_loss: 0.4562
Epoch 125/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1744 - val_accuracy: 0.8438 - val_loss: 0.4566
Epoch 126/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1742 - val_accuracy: 0.8438 - val_loss: 0.4568
Epoch 127/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9453 - loss: 0.1741 - val_accuracy: 0.8438 - val_loss: 0.4572
Epoch 128/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1739 - val_accuracy: 0.8438 - val_loss: 0.4575
Epoch 129/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1737 - val_accuracy: 0.8438 - val_loss: 0.4579
Epoch 130/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1736 - val_accuracy: 0.8438 - val_loss: 0.4582
Epoch 131/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1734 - val_accuracy: 0.8438 - val_loss: 0.4587
Epoch 132/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1733 - val_accuracy: 0.8438 - val_loss: 0.4590
Epoch 133/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1731 - val_accuracy: 0.8438 - val_loss: 0.4591
Epoch 134/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1730 - val_accuracy: 0.8438 - val_loss: 0.4595
Epoch 135/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.1728 - val_accuracy: 0.8438 - val_loss: 0.4598
Epoch 136/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1727 - val_accuracy: 0.8438 - val_loss: 0.4602
Epoch 137/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1725 - val_accuracy: 0.8438 - val_loss: 0.4604
Epoch 138/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.1724 - val_accuracy: 0.8438 - val_loss: 0.4607
Epoch 139/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9453 - loss: 0.1723 - val_accuracy: 0.8438 - val_loss: 0.4610
Epoch 140/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9453 - loss: 0.1721 - val_accuracy: 0.8438 - val_loss: 0.4611
Epoch 141/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9453 - loss: 0.1720 - val_accuracy: 0.8438 - val_loss: 0.4614
Epoch 142/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9453 - loss: 0.1718 - val_accuracy: 0.8438 - val_loss: 0.4617
Epoch 143/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9453 - loss: 0.1716 - val_accuracy: 0.8438 - val_loss: 0.4618
Epoch 144/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1715 - val_accuracy: 0.8438 - val_loss: 0.4622
Epoch 145/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1712 - val_accuracy: 0.8438 - val_loss: 0.4623
Epoch 146/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1711 - val_accuracy: 0.8438 - val_loss: 0.4623
Epoch 147/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9414 - loss: 0.1709 - val_accuracy: 0.8438 - val_loss: 0.4620
Epoch 148/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1707 - val_accuracy: 0.8438 - val_loss: 0.4619
Epoch 149/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1706 - val_accuracy: 0.8438 - val_loss: 0.4623
Epoch 150/150
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1704 - val_accuracy: 0.8438 - val_loss: 0.4619
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9000 - loss: 0.2404
========================
Final Test Loss: 0.24040833115577698
Final Test Accuracy: 0.8999999761581421

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


tf.keras.utils.set_random_seed(42)



model = Sequential([

    Dense(32, activation='relu', input_shape=(3,)),
    BatchNormalization(),

    Dense(16, activation='relu'),
    BatchNormalization(),

    Dense(8, activation='relu'),

    Dense(1, activation='sigmoid')
])


model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)



early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=40,
    restore_best_weights=True
)



history = model.fit(
    X_train,
    y_train,
    epochs=500,
    batch_size=4,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)



test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)


print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")


model.summary()

Epoch 1/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.3867 - loss: 0.9456 - val_accuracy: 0.2500 - val_loss: 0.7185
Epoch 2/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3906 - loss: 0.7828 - val_accuracy: 0.2812 - val_loss: 0.7267
Epoch 3/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4180 - loss: 0.7082 - val_accuracy: 0.3906 - val_loss: 0.7301
Epoch 4/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - loss: 0.6641 - val_accuracy: 0.4531 - val_loss: 0.7237
Epoch 5/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5742 - loss: 0.6327 - val_accuracy: 0.5938 - val_loss: 0.7129
Epoch 6/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6641 - loss: 0.6085 - val_accuracy: 0.6875 - val_loss: 0.7059
Epoch 7/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7188 - loss: 0.5875 - val_accuracy: 0.7500 - val_loss: 0.6996
Epoch 8/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7617 - loss: 0.5666 - val_accuracy: 0.7969 - val_loss: 0.6918
Epoch 9/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8047 - loss: 0.5450 - val_accuracy: 0.7969 - val_loss: 0.6817
Epoch 10/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8008 - loss: 0.5226 - val_accuracy: 0.8125 - val_loss: 0.6709
Epoch 11/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8242 - loss: 0.4967 - val_accuracy: 0.7969 - val_loss: 0.6543
Epoch 12/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8281 - loss: 0.4712 - val_accuracy: 0.8281 - val_loss: 0.6292
Epoch 13/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4414 - val_accuracy: 0.8438 - val_loss: 0.5893
Epoch 14/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.4124 - val_accuracy: 0.8594 - val_loss: 0.5537
Epoch 15/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8633 - loss: 0.3853 - val_accuracy: 0.8594 - val_loss: 0.5325
Epoch 16/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.3605 - val_accuracy: 0.8438 - val_loss: 0.5082
Epoch 17/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8750 - loss: 0.3406 - val_accuracy: 0.8594 - val_loss: 0.4926
Epoch 18/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8828 - loss: 0.3253 - val_accuracy: 0.8594 - val_loss: 0.4841
Epoch 19/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8867 - loss: 0.3111 - val_accuracy: 0.8438 - val_loss: 0.4758
Epoch 20/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8906 - loss: 0.2961 - val_accuracy: 0.8438 - val_loss: 0.4754
Epoch 21/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8906 - loss: 0.2840 - val_accuracy: 0.8281 - val_loss: 0.4788
Epoch 22/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2757 - val_accuracy: 0.8438 - val_loss: 0.4682
Epoch 23/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2691 - val_accuracy: 0.8281 - val_loss: 0.5153
Epoch 24/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9141 - loss: 0.2587 - val_accuracy: 0.8281 - val_loss: 0.4948
Epoch 25/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2486 - val_accuracy: 0.8125 - val_loss: 0.4996
Epoch 26/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9141 - loss: 0.2480 - val_accuracy: 0.8281 - val_loss: 0.4999
Epoch 27/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9219 - loss: 0.2352 - val_accuracy: 0.8125 - val_loss: 0.5005
Epoch 28/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9180 - loss: 0.2300 - val_accuracy: 0.8125 - val_loss: 0.5110
Epoch 29/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2255 - val_accuracy: 0.7969 - val_loss: 0.4970
Epoch 30/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2213 - val_accuracy: 0.8125 - val_loss: 0.5265
Epoch 31/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9219 - loss: 0.2161 - val_accuracy: 0.7969 - val_loss: 0.5142
Epoch 32/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9297 - loss: 0.2092 - val_accuracy: 0.8281 - val_loss: 0.5184
Epoch 33/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9258 - loss: 0.2074 - val_accuracy: 0.8281 - val_loss: 0.5255
Epoch 34/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9297 - loss: 0.2000 - val_accuracy: 0.8281 - val_loss: 0.5223
Epoch 35/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9375 - loss: 0.1957 - val_accuracy: 0.8281 - val_loss: 0.5225
Epoch 36/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1897 - val_accuracy: 0.8438 - val_loss: 0.5318
Epoch 37/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.1855 - val_accuracy: 0.8438 - val_loss: 0.5345
Epoch 38/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9414 - loss: 0.1807 - val_accuracy: 0.8438 - val_loss: 0.5405
Epoch 39/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.1766 - val_accuracy: 0.8438 - val_loss: 0.5593
Epoch 40/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9453 - loss: 0.1741 - val_accuracy: 0.8281 - val_loss: 0.5452
Epoch 41/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.1698 - val_accuracy: 0.8438 - val_loss: 0.5494
Epoch 42/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.1638 - val_accuracy: 0.8438 - val_loss: 0.5537
Epoch 43/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9570 - loss: 0.1594 - val_accuracy: 0.8281 - val_loss: 0.5453
Epoch 44/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9648 - loss: 0.1551 - val_accuracy: 0.8281 - val_loss: 0.5572
Epoch 45/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9648 - loss: 0.1502 - val_accuracy: 0.8281 - val_loss: 0.5598
Epoch 46/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9648 - loss: 0.1466 - val_accuracy: 0.8125 - val_loss: 0.5692
Epoch 47/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9648 - loss: 0.1425 - val_accuracy: 0.8125 - val_loss: 0.5733
Epoch 48/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9688 - loss: 0.1391 - val_accuracy: 0.7969 - val_loss: 0.5602
Epoch 49/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9570 - loss: 0.1393 - val_accuracy: 0.8125 - val_loss: 0.5971
Epoch 50/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9609 - loss: 0.1356 - val_accuracy: 0.8281 - val_loss: 0.5766
Epoch 51/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9531 - loss: 0.1354 - val_accuracy: 0.8438 - val_loss: 0.5916
Epoch 52/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9570 - loss: 0.1336 - val_accuracy: 0.8125 - val_loss: 0.5775
Epoch 53/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9648 - loss: 0.1226 - val_accuracy: 0.8438 - val_loss: 0.5785
Epoch 54/500
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9648 - loss: 0.1229 - val_accuracy: 0.8281 - val_loss: 0.5969
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9000 - loss: 0.4138
========================
Final Test Loss: 0.4137990474700928
Final Test Accuracy: 0.8999999761581421
========================

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_36 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_39 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,789 (10.90 KB)

 Trainable params: 897 (3.50 KB)

 Non-trainable params: 96 (384.00 B)

 Optimizer params: 1,796 (7.02 KB)

In [43]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


tf.keras.utils.set_random_seed(42)


model = Sequential([
    Dense(6, activation='relu', input_shape=(3,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])


model.compile(
    optimizer=Adam(learning_rate=0.0003),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=40,
    restore_best_weights=True
)


history = model.fit(
    X_train,
    y_train,
    epochs=500,
    batch_size=8,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("========================")
print("Final Test Loss:", test_loss)
print("Final Test Accuracy:", test_accuracy)
print("========================")

Epoch 1/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.3750 - loss: 0.7262 - val_accuracy: 0.2656 - val_loss: 0.7778
Epoch 2/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4102 - loss: 0.7092 - val_accuracy: 0.3906 - val_loss: 0.7571
Epoch 3/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4492 - loss: 0.6931 - val_accuracy: 0.4688 - val_loss: 0.7378
Epoch 4/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5039 - loss: 0.6779 - val_accuracy: 0.5156 - val_loss: 0.7199
Epoch 5/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6094 - loss: 0.6635 - val_accuracy: 0.5781 - val_loss: 0.7031
Epoch 6/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6445 - loss: 0.6499 - val_accuracy: 0.6250 - val_loss: 0.6877
Epoch 7/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6562 - loss: 0.6368 - val_accuracy: 0.6406 - val_loss: 0.6730
Epoch 8/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6797 - loss: 0.6242 - val_accuracy: 0.6562 - val_loss: 0.6592
Epoch 9/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6953 - loss: 0.6119 - val_accuracy: 0.6562 - val_loss: 0.6456
Epoch 10/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7188 - loss: 0.5996 - val_accuracy: 0.6875 - val_loss: 0.6317
Epoch 11/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7227 - loss: 0.5876 - val_accuracy: 0.7031 - val_loss: 0.6184
Epoch 12/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7461 - loss: 0.5758 - val_accuracy: 0.7188 - val_loss: 0.6057
Epoch 13/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7773 - loss: 0.5639 - val_accuracy: 0.7500 - val_loss: 0.5936
Epoch 14/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7852 - loss: 0.5520 - val_accuracy: 0.7500 - val_loss: 0.5819
Epoch 15/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7930 - loss: 0.5404 - val_accuracy: 0.7500 - val_loss: 0.5708
Epoch 16/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7969 - loss: 0.5292 - val_accuracy: 0.7344 - val_loss: 0.5603
Epoch 17/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8008 - loss: 0.5185 - val_accuracy: 0.7344 - val_loss: 0.5501
Epoch 18/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8125 - loss: 0.5083 - val_accuracy: 0.7500 - val_loss: 0.5405
Epoch 19/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8164 - loss: 0.4984 - val_accuracy: 0.7656 - val_loss: 0.5313
Epoch 20/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8203 - loss: 0.4889 - val_accuracy: 0.7812 - val_loss: 0.5227
Epoch 21/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8242 - loss: 0.4799 - val_accuracy: 0.7812 - val_loss: 0.5148
Epoch 22/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8281 - loss: 0.4713 - val_accuracy: 0.7969 - val_loss: 0.5075
Epoch 23/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8281 - loss: 0.4632 - val_accuracy: 0.7969 - val_loss: 0.5008
Epoch 24/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4555 - val_accuracy: 0.7969 - val_loss: 0.4946
Epoch 25/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4482 - val_accuracy: 0.7969 - val_loss: 0.4889
Epoch 26/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4413 - val_accuracy: 0.7969 - val_loss: 0.4837
Epoch 27/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.4347 - val_accuracy: 0.7969 - val_loss: 0.4789
Epoch 28/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4284 - val_accuracy: 0.7969 - val_loss: 0.4744
Epoch 29/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.4225 - val_accuracy: 0.7969 - val_loss: 0.4702
Epoch 30/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4169 - val_accuracy: 0.7969 - val_loss: 0.4663
Epoch 31/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4116 - val_accuracy: 0.7969 - val_loss: 0.4625
Epoch 32/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4066 - val_accuracy: 0.7969 - val_loss: 0.4590
Epoch 33/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.4018 - val_accuracy: 0.7969 - val_loss: 0.4558
Epoch 34/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3972 - val_accuracy: 0.7969 - val_loss: 0.4529
Epoch 35/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3928 - val_accuracy: 0.7969 - val_loss: 0.4502
Epoch 36/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3886 - val_accuracy: 0.8125 - val_loss: 0.4478
Epoch 37/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8320 - loss: 0.3846 - val_accuracy: 0.8125 - val_loss: 0.4456
Epoch 38/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3807 - val_accuracy: 0.8125 - val_loss: 0.4436
Epoch 39/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3769 - val_accuracy: 0.8125 - val_loss: 0.4416
Epoch 40/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3734 - val_accuracy: 0.8125 - val_loss: 0.4398
Epoch 41/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3700 - val_accuracy: 0.8125 - val_loss: 0.4383
Epoch 42/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8359 - loss: 0.3668 - val_accuracy: 0.8125 - val_loss: 0.4369
Epoch 43/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3638 - val_accuracy: 0.8125 - val_loss: 0.4357
Epoch 44/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3609 - val_accuracy: 0.8125 - val_loss: 0.4345
Epoch 45/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8438 - loss: 0.3581 - val_accuracy: 0.8125 - val_loss: 0.4335
Epoch 46/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3554 - val_accuracy: 0.8125 - val_loss: 0.4326
Epoch 47/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3530 - val_accuracy: 0.8125 - val_loss: 0.4319
Epoch 48/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8359 - loss: 0.3508 - val_accuracy: 0.8125 - val_loss: 0.4313
Epoch 49/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3486 - val_accuracy: 0.8125 - val_loss: 0.4308
Epoch 50/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3465 - val_accuracy: 0.8125 - val_loss: 0.4304
Epoch 51/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3446 - val_accuracy: 0.8125 - val_loss: 0.4300
Epoch 52/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3428 - val_accuracy: 0.8125 - val_loss: 0.4297
Epoch 53/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3410 - val_accuracy: 0.8125 - val_loss: 0.4295
Epoch 54/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3392 - val_accuracy: 0.8125 - val_loss: 0.4293
Epoch 55/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3376 - val_accuracy: 0.8125 - val_loss: 0.4292
Epoch 56/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.3361 - val_accuracy: 0.8125 - val_loss: 0.4291
Epoch 57/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3347 - val_accuracy: 0.8125 - val_loss: 0.4290
Epoch 58/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3334 - val_accuracy: 0.8125 - val_loss: 0.4290
Epoch 59/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8398 - loss: 0.3321 - val_accuracy: 0.8125 - val_loss: 0.4291
Epoch 60/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3309 - val_accuracy: 0.8125 - val_loss: 0.4291
Epoch 61/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3298 - val_accuracy: 0.8125 - val_loss: 0.4292
Epoch 62/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3286 - val_accuracy: 0.8125 - val_loss: 0.4293
Epoch 63/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3276 - val_accuracy: 0.8125 - val_loss: 0.4294
Epoch 64/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3265 - val_accuracy: 0.8125 - val_loss: 0.4296
Epoch 65/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3256 - val_accuracy: 0.8125 - val_loss: 0.4297
Epoch 66/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3247 - val_accuracy: 0.8125 - val_loss: 0.4299
Epoch 67/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3238 - val_accuracy: 0.8125 - val_loss: 0.4300
Epoch 68/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3230 - val_accuracy: 0.8125 - val_loss: 0.4302
Epoch 69/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3222 - val_accuracy: 0.8125 - val_loss: 0.4304
Epoch 70/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8438 - loss: 0.3214 - val_accuracy: 0.8125 - val_loss: 0.4306
Epoch 71/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8438 - loss: 0.3207 - val_accuracy: 0.8125 - val_loss: 0.4308
Epoch 72/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3199 - val_accuracy: 0.8125 - val_loss: 0.4309
Epoch 73/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3192 - val_accuracy: 0.8125 - val_loss: 0.4311
Epoch 74/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3185 - val_accuracy: 0.8125 - val_loss: 0.4313
Epoch 75/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3178 - val_accuracy: 0.8125 - val_loss: 0.4314
Epoch 76/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3171 - val_accuracy: 0.8125 - val_loss: 0.4316
Epoch 77/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3165 - val_accuracy: 0.8125 - val_loss: 0.4318
Epoch 78/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8477 - loss: 0.3159 - val_accuracy: 0.8125 - val_loss: 0.4319
Epoch 79/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3152 - val_accuracy: 0.8125 - val_loss: 0.4319
Epoch 80/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3146 - val_accuracy: 0.8125 - val_loss: 0.4320
Epoch 81/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3140 - val_accuracy: 0.8125 - val_loss: 0.4320
Epoch 82/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3135 - val_accuracy: 0.8125 - val_loss: 0.4320
Epoch 83/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3129 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 84/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3124 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 85/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3119 - val_accuracy: 0.8125 - val_loss: 0.4321
Epoch 86/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3114 - val_accuracy: 0.8125 - val_loss: 0.4322
Epoch 87/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3109 - val_accuracy: 0.8125 - val_loss: 0.4322
Epoch 88/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3104 - val_accuracy: 0.8125 - val_loss: 0.4323
Epoch 89/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3099 - val_accuracy: 0.8125 - val_loss: 0.4324
Epoch 90/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3094 - val_accuracy: 0.8125 - val_loss: 0.4325
Epoch 91/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3090 - val_accuracy: 0.8125 - val_loss: 0.4327
Epoch 92/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3085 - val_accuracy: 0.8125 - val_loss: 0.4328
Epoch 93/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3081 - val_accuracy: 0.8125 - val_loss: 0.4329
Epoch 94/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3077 - val_accuracy: 0.8125 - val_loss: 0.4330
Epoch 95/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3072 - val_accuracy: 0.8125 - val_loss: 0.4331
Epoch 96/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3068 - val_accuracy: 0.8125 - val_loss: 0.4332
Epoch 97/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8516 - loss: 0.3064 - val_accuracy: 0.8125 - val_loss: 0.4333
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7875 - loss: 0.4465
========================
Final Test Loss: 0.446494996547699
Final Test Accuracy: 0.7875000238418579
========================